"use client";

import FoyerFields, { foyerInitial, lireFoyer } from '@/components/FoyerFields';
import React, { useMemo, useState } from 'react';
import MainLayout from '@/components/MainLayout';
import { liquidationMeuble, planAmortissementMeuble, plusValueMeuble, type TypeMeuble } from '@/lib/lmnp';

const euros=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
const initial={type:'classique',recettes:'12000',n1:'12000',n2:'12000',conditionsMicro:false,autresRevenus:'40000',charges:'2000',fraisReel:'600',amortissement:'5000',reportAmortissement:'0',deficitImputable:'0',tmi:'30',ps:'18.6',socialForce:false,cotisationsMicro:'',cotisationsReel:'',cotisationsDeductibles:'',prix:'250000',terrain:'20',mobilier:'15000',dureeImmo:'40',dureeMobilier:'10',acquisition:'250000',vente:'300000',fraisAcquisition:'18750',fraisVente:'0',travaux:'0',reintegration:'',exceptionResidence:false,dateAcquisition:'2020-01-01',dateVente:'2026-09-08',psVente:'17.2'};
type Formulaire=typeof initial;
const stockage='notariaprime-lmnp-v2';

export default function LMNPPage(){
  const [foyer,setFoyer]=useState(foyerInitial);
  const [form,setForm]=useState<Formulaire>(initial);
  const [tab,setTab]=useState('annuel');
  const [calculer,setCalculer]=useState(false);
  const [message,setMessage]=useState('');
  const update=(key:keyof Formulaire,value:string|boolean)=>{setForm(f=>({...f,[key]:value}));setCalculer(false);setMessage('');};
  const champ=(key:keyof Formulaire,label:string,aide?:string,max?:number)=><label className="block text-sm font-medium" key={key}>{label}<input aria-label={label} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3" type="number" min="0" max={max} step="any" value={String(form[key])} onChange={e=>update(key,e.target.value)}/>{aide&&<span className="mt-1 block text-xs font-normal text-slate-600">{aide}</span>}</label>;
  const caseACocher=(key:keyof Formulaire,label:string)=><label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={Boolean(form[key])} onChange={e=>update(key,e.target.checked)}/>{label}</label>;
  const n=(key:keyof Formulaire)=>Number(form[key]);
  const resultat=useMemo(()=>{
    if(!calculer)return {annuel:null,pv:null,erreur:''};
    try{
      if(tab==='annuel'){
        for(const key of ['recettes','n1','n2','autresRevenus','charges','fraisReel','amortissement','reportAmortissement','deficitImputable'] as const)if(!form[key].trim())throw Error('Renseignez tous les montants annuels ; saisissez zéro en l’absence de montant.');
        return {annuel:liquidationMeuble({foyer:lireFoyer(foyer),type:form.type as TypeMeuble,recettes:Number(form.recettes),n1:Number(form.n1),n2:Number(form.n2),conditionsMicro:form.conditionsMicro,autresRevenus:Number(form.autresRevenus),charges:Number(form.charges),fraisReel:Number(form.fraisReel),amortissement:Number(form.amortissement),reportAmortissement:Number(form.reportAmortissement),deficitImputable:Number(form.deficitImputable),tmi:Number(form.tmi),ps:Number(form.ps),socialForce:form.socialForce,cotisationsMicro:form.cotisationsMicro.trim()?Number(form.cotisationsMicro):undefined,cotisationsReel:form.cotisationsReel.trim()?Number(form.cotisationsReel):undefined,cotisationsDeductibles:form.cotisationsDeductibles.trim()?Number(form.cotisationsDeductibles):undefined}),pv:null,erreur:''};
      }
      if(tab==='vente'){
        for(const key of ['acquisition','vente','fraisAcquisition','fraisVente','travaux','reintegration'] as const)if(!form[key].trim())throw Error('Renseignez tous les montants de la vente, dont les amortissements à réintégrer (zéro accepté).');
        return {annuel:null,pv:plusValueMeuble({acquisition:Number(form.acquisition),vente:Number(form.vente),fraisAcquisition:Number(form.fraisAcquisition),fraisVente:Number(form.fraisVente),travaux:Number(form.travaux),reintegration:Number(form.reintegration),exceptionResidence:form.exceptionResidence,dateAcquisition:form.dateAcquisition,dateVente:form.dateVente,ps:Number(form.psVente)}),erreur:''};
      }
      return {annuel:null,pv:null,erreur:''};
    }catch(e){return {annuel:null,pv:null,erreur:e instanceof Error?e.message:'Vérifiez les données.'};}
  },[form,calculer,tab,foyer]);
  const plan=useMemo(()=>{try{return planAmortissementMeuble(Number(form.prix),Number(form.terrain),Number(form.mobilier),Number(form.dureeImmo),Number(form.dureeMobilier));}catch{return null;}},[form.prix,form.terrain,form.mobilier,form.dureeImmo,form.dureeMobilier]);
  const r=resultat.annuel,pv=resultat.pv;
  const cotisant=form.socialForce||(n('recettes')>23000&&(form.type!=='classique'||n('recettes')>n('autresRevenus')));
  const sauvegarder=()=>{try{localStorage.setItem(stockage,JSON.stringify(form));setMessage('Simulation enregistrée sur cet appareil. Le mode foyer doit être renseigné à nouveau après chargement.');}catch{setMessage('Le navigateur ne permet pas cet enregistrement.');}};
  const charger=()=>{try{const raw=localStorage.getItem(stockage);if(!raw){setMessage('Aucune simulation enregistrée dans cette version. Les anciens calculs ne sont pas réutilisés automatiquement.');return;}const data=JSON.parse(raw);const valid=Object.keys(initial).every(k=>typeof data[k]===typeof initial[k as keyof Formulaire]);if(!valid)throw Error();setForm(data);setFoyer(foyerInitial);setCalculer(false);setMessage('Simulation chargée ; relancez le calcul.');}catch{setMessage('La sauvegarde est illisible.');}};
  return <MainLayout><div className="mx-auto max-w-6xl px-4 py-10 text-slate-800">
    <h1 className="text-3xl font-bold">Location meublée : LMNP et LMP</h1>
    <p className="mt-3">Comparez le micro-BIC et le réel sur les recettes de 2026, puis estimez une revente sous le régime des particuliers. Les exemples préremplis sont à remplacer par les données de votre activité.</p>
    <nav aria-label="Sections location meublée" className="my-6 flex flex-wrap gap-2 print:hidden">{[['annuel','Fiscalité annuelle'],['amortissement','Amortissement'],['vente','Revente LMNP'],['methode','Règles et sources']].map(([id,label])=><button key={id} onClick={()=>{setTab(id);setCalculer(false);}} className={`rounded-lg px-4 py-3 ${tab===id?'bg-indigo-700 text-white':'bg-slate-100'}`}>{label}</button>)}</nav>
    {tab==='annuel'&&<><FoyerFields value={foyer} onChange={v=>{setFoyer(v);setCalculer(false);}}/>
      <div className="grid gap-6 md:grid-cols-2">
        <section className="space-y-4 rounded-2xl border bg-slate-50 p-5"><h2 className="text-xl font-semibold">Activité et recettes du foyer</h2>
          <label className="block text-sm font-medium">Type de location<select aria-label="Type de location" value={form.type} onChange={e=>update('type',e.target.value)} className="mt-2 w-full rounded-lg border bg-white p-3"><option value="classique">Meublé de longue durée</option><option value="tourisme_classe">Meublé de tourisme classé</option><option value="tourisme_non_classe">Meublé de tourisme non classé</option></select></label>
          {champ('recettes','Recettes annuelles 2026 (€)','Total des loyers et charges encaissés, tous meublés de même catégorie du foyer. Année complète ; sans TVA.')}
          {champ('n1','Recettes de référence 2025 (€)','Montant annualisé si nécessaire pour apprécier le seuil du micro.')}
          {champ('n2','Recettes de référence 2024 (€)')}
          {caseACocher('conditionsMicro','Je confirme les autres conditions du micro : exploitation individuelle éligible, absence d’option pour le réel en cours et d’activités mixtes à agréger. Une indivision relève du réel.')}
          {champ('autresRevenus','Autres revenus du foyer retenus pour le statut LMP (€)','Revenus nets catégoriels : traitements, salaires, pensions et rentes, article 62, autres BIC, BA et BNC. Hors revenus fonciers et capitaux mobiliers. Cas résident fiscal français.')}
          {champ('tmi','Taux marginal d’imposition (%)','Approximation à taux constant, hors franchissement de tranche, décote et CSG déductible.',45)}
          <label className="block text-sm">Prélèvements sociaux hors affiliation<select aria-label="Prélèvements sociaux hors affiliation" className="mt-2 w-full rounded-lg border bg-white p-3" value={form.ps} onChange={e=>update('ps',e.target.value)}><option value="18.6">18,6 % — cas général BIC meublé</option><option value="7.5">7,5 % — affiliation étrangère ouvrant droit à exonération CSG/CRDS</option></select></label>
        </section>
        <section className="space-y-4 rounded-2xl border bg-slate-50 p-5"><h2 className="text-xl font-semibold">Charges et comptabilité</h2>
          {champ('charges','Charges annuelles communes aux deux régimes (€)','Dépenses décaissées et déductibles au réel : intérêts et assurance du prêt, CFE, taxe foncière, entretien, assurance, charges de copropriété et gestion. Hors capital remboursé, immobilisations et cotisations personnelles ci-dessous.')}
          {champ('fraisReel','Frais supplémentaires propres au réel (€)','Comptabilité et autres coûts réellement supportés seulement au réel.')}
          {champ('amortissement','Dotation comptable de l’exercice (€)','Immeuble hors terrain et mobilier. Utilisez votre plan comptable ou l’aide de l’onglet Amortissement.')}
          {champ('reportAmortissement','Amortissements antérieurs reportables (€)','Stock non encore déduit sous l’article 39 C ; sans limite de durée pendant l’activité.')}
          {champ('deficitImputable','Déficits LMNP antérieurs encore imputables (€)','Uniquement les déficits justifiés des dix années précédentes, non consommés et non expirés. Non utilisé en LMP ; le tableau comptable conserve les millésimes.')}
          {caseACocher('socialForce','Mon activité relève déjà d’un régime de cotisations sociales (affiliation à confirmer avec l’Urssaf).')}
          {cotisant&&<div className="space-y-4 border-t pt-4"><p className="text-sm">Cotisations requises : LMP ou tourisme au-delà de 23 000 €, même si le statut fiscal reste LMNP. Saisissez les estimations correspondant à chaque régime ; aucun taux forfaitaire de 40 % n’est appliqué.</p>
            {champ('cotisationsMicro','Cotisations annuelles avec micro-BIC (€)','Si le micro fiscal est applicable ; ne présume pas une éligibilité au micro-social.')}
            {champ('cotisationsReel','Cotisations annuelles au réel (€)','Total décaissé, contributions incluses, même en cas de résultat nul.')}
            {champ('cotisationsDeductibles','Part fiscalement déductible au réel (€)','Montant précédent diminué notamment de la CSG/CRDS non déductible ; ne pas inclure dans les charges communes.')}
            <a className="text-indigo-700 underline" href="https://www.urssaf.fr/accueil/outils-documentation/simulateurs/cotisations-economie-collaborati.html" target="_blank" rel="noreferrer">Estimer les cotisations auprès de l’Urssaf</a>
          </div>}
        </section>
      </div>
      <p className="mt-4 text-sm text-slate-600">Périmètre : une catégorie de location, sans prestations para-hôtelières, sans occupation privée ni exonération de location d’une partie de la résidence principale. Recettes et dépenses sont supposées encaissées/payées dans l’année. Une activité nouvelle, mixte, une société ou une situation internationale demandent une analyse adaptée.</p>
    </>}
    {tab==='amortissement'&&<section className="space-y-5 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Aide à la dotation annuelle</h2><p>Calcul linéaire indicatif sur une année entière à partir de durées que vous choisissez. Ce n’est pas un barème légal : la ventilation par composants et leur durée d’utilisation doivent être justifiées. Les remplacements, travaux, frais immobilisés et proratas de mise en service sont à intégrer dans le plan comptable.</p><div className="grid gap-4 md:grid-cols-2">{champ('prix','Valeur immobilière inscrite au bilan (€)')}{champ('terrain','Quote-part du terrain (%)',undefined,100)}{champ('mobilier','Valeur du mobilier (€)')}{champ('dureeImmo','Durée moyenne immobilière (années)')}{champ('dureeMobilier','Durée du mobilier (années)')}</div>{plan?<><p>Base immobilière amortissable : <strong>{euros(plan.base)}</strong>. Dotation immobilière : {euros(plan.immo)} ; mobilier : {euros(plan.mobilier)} ; total annuel théorique : <strong>{euros(plan.total)}</strong>.</p><button className="rounded-lg bg-indigo-700 px-4 py-3 text-white" onClick={()=>{update('amortissement',plan.total.toFixed(2));setTab('annuel');}}>Utiliser cette dotation dans le calcul annuel</button></>:<p role="alert">Vérifiez les montants, le terrain entre 0 et 100 % et les durées strictement positives.</p>}<p className="text-sm">La dotation comptable n’est pas nécessairement déductible en totalité. Le calcul annuel applique le plafond de l’article 39 C. La revente utilise les amortissements réellement déduits et réintégrables, saisis séparément.</p></section>}
    {tab==='vente'&&<section className="space-y-5 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Revente d’un immeuble sous statut LMNP à la cession</h2><p>Un propriétaire, en pleine propriété, cédant la totalité d’un immeuble bâti acquis à titre onéreux. La vente du mobilier est exclue. Pour une indivision, un démembrement ou une exonération personnelle, utilisez le <a className="text-indigo-700 underline" href="/plusvalue">calculateur de plus-value immobilière</a>. En LMP à la cession, utilisez le <a className="text-indigo-700 underline" href="/plusvalue-pro">module professionnel</a> : une détention de cinq ans ne suffit pas à exonérer automatiquement la vente.</p><div className="grid gap-4 md:grid-cols-2">{champ('acquisition','Prix d’acquisition immobilier (€)')}{champ('vente','Prix de vente immobilier (€)')}{champ('fraisAcquisition','Frais d’acquisition retenus pour la plus-value (€)','Frais réels admissibles ou forfait de 7,5 % pour un achat ; vérifiez le montant prérempli.')}{champ('fraisVente','Frais de cession admissibles (€)')}{champ('travaux','Travaux retenus pour la plus-value (€)','Dépenses fiscalement admissibles ou forfait de 15 % après plus de cinq ans. Évitez tout double compte.')}{champ('reintegration','Amortissements immobiliers à réintégrer (€)','Montant effectivement déduit et réintégrable sous CGI 150 VB III, attesté par la comptabilité. Hors mobilier, reports non déduits et amortissements de travaux visés par l’exception du même III. Zéro si aucun.')}{(['dateAcquisition','dateVente'] as const).map((key,i)=><label className="text-sm" key={key}>{i?'Date de vente':'Date d’acquisition'}<input aria-label={i?'Date de vente':'Date d’acquisition'} type="date" min={key==='dateVente'?'2026-01-01':undefined} className="mt-2 block w-full rounded-lg border p-3" value={form[key]} onChange={e=>update(key,e.target.value)}/></label>)}</div>{caseACocher('exceptionResidence','Le bien relève effectivement d’une des résidences étudiantes, seniors ou personnes handicapées expressément exclues de la réintégration par CGI 150 VB III (qualification vérifiée).')}<label className="block text-sm">Taux social de la plus-value<select aria-label="Taux social de la plus-value" className="mt-2 block rounded-lg border p-3" value={form.psVente} onChange={e=>update('psVente',e.target.value)}><option value="17.2">17,2 % — cas général</option><option value="7.5">7,5 % — affiliation étrangère éligible</option></select></label><p className="text-sm">Règles 2026 constantes, sans anticipation d’une évolution législative. Le net vendeur est calculé avant remboursement du capital du prêt et autres frais non saisis. Les exonérations de résidence principale, premier remploi, non-résident et abattements exceptionnels ne sont pas appliqués ici.</p></section>}
    {(tab==='annuel'||tab==='vente')&&<div className="my-6 flex flex-wrap gap-3 print:hidden"><button onClick={()=>setCalculer(true)} className="rounded-lg bg-indigo-700 px-5 py-3 font-semibold text-white">Calculer</button><button className="rounded-lg border px-4 py-3" onClick={sauvegarder}>Enregistrer</button><button className="rounded-lg border px-4 py-3" onClick={charger}>Charger</button>{(r||pv)&&<button className="rounded-lg border px-4 py-3" onClick={()=>window.print()}>Imprimer / PDF</button>}</div>}
    {message&&<p role="status">{message}</p>}{resultat.erreur&&<p role="alert" className="my-4 rounded-lg bg-red-50 p-4 text-red-800">{resultat.erreur}</p>}
    {r&&<section className="space-y-4 rounded-2xl border p-5" aria-label="Résultats annuels"><h2 className="text-xl font-semibold">Résultat annuel — statut fiscal {r.lmp?'LMP':'LMNP'}</h2><p>{r.cotisant?'Cotisations sociales saisies, sans cumul avec les prélèvements du patrimoine.':'Prélèvements sociaux du patrimoine appliqués au résultat fiscal positif.'}</p><p>Micro : abattement {r.micro.taux*100} %, minimum 305 € limité aux recettes ; seuil de référence {euros(r.micro.plafond)}. {r.micro.eligible?'Les données et conditions confirmées permettent la comparaison.':'Micro non validé : montants théoriques, aucune économie recommandée.'}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Montant annuel</th><th>Micro-BIC{!r.micro.eligible?' (théorique)':''}</th><th>Réel</th></tr></thead><tbody>{[
      ['Recettes',n('recettes'),n('recettes')],['Charges décaissées hors cotisations',n('charges'),n('charges')+n('fraisReel')],['Abattement / amortissement déduit',r.micro.abattement,r.amortissementDeduit],['Base imposable après reports',r.micro.base,r.baseReel],[foyer.actif?'Variation d’IR du foyer':'Impôt estimé à la TMI',r.irMicro,r.irReel],['Prélèvements ou cotisations',r.socialMicro,r.socialReel],['Trésorerie après impôts, avant capital du prêt',r.cashMicro,r.cashReel]
    ].map(([label,a,b])=><tr key={String(label)} className="border-b"><th className="p-3 text-left font-normal">{label}</th><td className="p-3 whitespace-nowrap">{euros(Number(a))}</td><td className="p-3 whitespace-nowrap">{euros(Number(b))}</td></tr>)}</tbody></table></div>{r.economieReel!==null&&<p className="font-semibold">{Math.abs(r.economieReel)<.005?'Trésoreries équivalentes dans ces hypothèses.':`${r.economieReel>0?'Réel':'Micro-BIC'} : ${euros(Math.abs(r.economieReel))} de trésorerie annuelle supplémentaire dans ces hypothèses.`}</p>}<p>Amortissements restant à reporter : {euros(r.reportAmortissement)}. Déficit de l’exercice hors amortissement : {euros(r.deficitCree)}. {r.lmp?'En LMP, l’imputation éventuelle sur le revenu global et ses reports ne sont pas chiffrés ici.':`Déficits LMNP antérieurs utilisés : ${euros(r.deficitUtilise)} ; solde : ${euros(r.deficitRestant)}. Conservez leurs années d’origine pour l’expiration à dix ans.`}</p><p className="text-sm text-slate-600">Comparaison annuelle ; les frais de revente, les variations futures d’amortissement, de recettes ou de statut et les droits sociaux ne sont pas intégrés à cet écart. L’avantage fiscal n’est pas une garantie de rentabilité.</p></section>}
    {pv&&<section aria-label="Résultat revente" className="space-y-3 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Estimation de la plus-value LMNP</h2><p>Détention : {pv.annees} années révolues ; amortissements réintégrés : {euros(pv.reintegration)}.</p><p>Plus-value brute : <strong>{euros(pv.brute)}</strong>. Abattements : {pv.abattements.ir} % pour l’impôt et {pv.abattements.ps} % pour les prélèvements sociaux.</p><p>Impôt : {euros(pv.ir)} ; prélèvements sociaux : {euros(pv.social)} ; surtaxe : {euros(pv.surtaxe)}.</p><p className="text-lg font-semibold">Total à payer : {euros(pv.total)} — net vendeur estimé : {euros(pv.net)}</p></section>}
    {tab==='methode'&&<section className="space-y-5 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Règles vérifiées au 8 septembre 2026</h2>
      <p>Le statut LMP suppose que les recettes meublées du foyer dépassent à la fois 23 000 € et les autres revenus catégoriels visés par CGI 155 IV. Il est apprécié chaque année. Le régime social obéit aussi à ses propres critères : en courte durée, dépasser 23 000 € peut imposer des cotisations même sans statut fiscal LMP.</p>
      <p>Micro-BIC 2026 : 50 % d’abattement et seuil de 83 600 € pour les meublés classés et de longue durée ; 30 % et 15 000 € pour le tourisme non classé, y compris hors zone tendue. Le seuil s’apprécie sur N−1 ou N−2, avec annualisation lorsque requise. Le minimum d’abattement est de 305 €. L’éligibilité fiscale ne garantit pas l’accès au micro-social. Une option pour le réel est annuelle et se renouvelle tacitement ; les délais de renonciation doivent être respectés.</p>
      <p>Au réel, le terrain n’est pas amortissable. Les dotations et reports d’amortissements déduits ne peuvent pas créer ou aggraver le déficit de location. Les déficits LMNP hors amortissement sont imputables sur les bénéfices LMNP des dix années suivantes. Le montant antérieur saisi doit déjà exclure les reports expirés ; leur suivi par millésime reste comptable. Le déficit LMP peut relever d’une imputation sur le revenu global, que cette estimation au TMI ne chiffre pas.</p>
      <p>À la revente LMNP, CGI 150 VB III minore le prix d’acquisition de certains amortissements immobiliers effectivement déduits. Il existe des exceptions précises, notamment pour certaines résidences et certains travaux : tout « logement senior » n’est pas automatiquement exclu. Les amortissements non déduits et le mobilier ne doivent pas être ajoutés au montant réintégrable de l’immeuble. Le régime de plus-value dépend du statut à la cession ; l’exonération LMP de l’article 151 septies exige notamment une durée d’activité et des recettes moyennes, et ne supprime pas mécaniquement toutes les cotisations.</p>
      <ul className="list-disc space-y-2 pl-5">
        <li><a className="text-indigo-700 underline" href="https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000054373853/2026-07-01">CGI 50-0 : micro-BIC et abattements</a></li>
        <li><a className="text-indigo-700 underline" href="https://bofip.impots.gouv.fr/bofip/14069-PGP.html/identifiant=BOI-BAREME-000044-20260819">BOFiP : seuils des recettes 2026 à 2028</a></li>
        <li><a className="text-indigo-700 underline" href="https://bofip.impots.gouv.fr/bofip/3610-PGP.html/identifiant=BOI-BIC-CHAMP-40-20-20260819">BOFiP : amortissements et déficits en location meublée</a></li>
        <li><a className="text-indigo-700 underline" href="https://www.impots.gouv.fr/particulier/les-regimes-dimposition">DGFiP : régimes fiscaux et sociaux du meublé</a></li>
        <li><a className="text-indigo-700 underline" href="https://www.impots.gouv.fr/particulier/questions/je-donne-un-bien-en-location-dois-je-payer-des-prelevements-sociaux">DGFiP : prélèvements sociaux</a></li>
        <li><a className="text-indigo-700 underline" href="https://www.impots.gouv.fr/particulier/questions/je-vends-mon-bien-immobilier-vais-je-payer-de-la-plus-value-immobiliere">DGFiP : plus-values et résidences exclues de la réintégration</a></li>
      </ul>
    </section>}
  </div></MainLayout>;
}
