"use client";
import React,{useMemo,useState} from 'react';
import MainLayout from '@/components/MainLayout';
import {echeancierPret} from '@/lib/pret';
const euros=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
const initial={capital:'200000',mois:'240',taux:'3',assurance:'0.3',assuranceRestant:false,frais:'1000'};
export default function PretPage(){
 const [f,setF]=useState(initial),[calculer,setCalculer]=useState(false),[tableau,setTableau]=useState(false);
 const update=(k:keyof typeof initial,v:string|boolean)=>{setF(x=>({...x,[k]:v}));setCalculer(false);};
 const champ=(k:Exclude<keyof typeof initial,'assuranceRestant'>,label:string,aide?:string)=><label className="block text-sm font-medium">{label}<input aria-label={label} type="number" min="0" step="any" className="mt-2 w-full rounded-lg border bg-white p-3" value={f[k]} onChange={e=>update(k,e.target.value)}/>{aide&&<span className="mt-1 block text-xs font-normal text-slate-600">{aide}</span>}</label>;
 const resultat=useMemo(()=>{if(!calculer)return {r:null,erreur:''};try{for(const v of Object.values(f))if(typeof v==='string'&&!v.trim())throw Error('Renseignez tous les champs ; zéro est accepté pour taux, assurance et frais.');return {r:echeancierPret({capital:Number(f.capital),mois:Number(f.mois),taux:Number(f.taux),assurance:Number(f.assurance),assuranceRestant:f.assuranceRestant,frais:Number(f.frais)}),erreur:''};}catch(e){return {r:null,erreur:e instanceof Error?e.message:'Vérifiez les paramètres.'};}},[f,calculer]);
 const r=resultat.r;
 const exporter=()=>{if(!r)return;const lignes=['Mois;Capital;Interets;Assurance;Paiement;Capital restant',...r.lignes.map(l=>[l.mois,l.capital,l.interets,l.assurance,l.paiement,l.restant].map(v=>String(v).replace('.',',')).join(';'))];const url=URL.createObjectURL(new Blob(['\uFEFF'+lignes.join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='notariaprime-echeancier.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <MainLayout><div className="mx-auto max-w-6xl px-4 py-10 text-slate-800"><h1 className="text-3xl font-bold">Calculateur de prêt immobilier</h1><p className="mt-3">Prêt amortissable à taux fixe, déblocage unique et échéances mensuelles à terme échu. Les valeurs préremplies sont des exemples, à remplacer par votre offre bancaire.</p><section className="mt-6 grid gap-5 rounded-2xl border bg-slate-50 p-5 md:grid-cols-2">{champ('capital','Capital emprunté (€)')}{champ('mois','Durée en mois','Nombre entier ; 240 mois correspondent à 20 ans.')}{champ('taux','Taux nominal annuel (%)','Taux contractuel hors assurance, conservé quand vous modifiez la durée.')}{champ('assurance','Taux annuel d’assurance (%)','Taux total à la quotité retenue pour tous les coemprunteurs, constant sur la durée.')}{champ('frais','Frais initiaux du financement (€)','Dossier, garantie, courtage et autres frais saisis, payés au déblocage. Hors frais d’acquisition du logement.')}<label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={f.assuranceRestant} onChange={e=>update('assuranceRestant',e.target.checked)}/>Assurance calculée sur le capital restant dû au début de chaque mois (sinon sur le capital initial).</label></section><div className="my-6 flex flex-wrap gap-3 print:hidden"><button className="rounded-lg bg-indigo-700 px-5 py-3 font-semibold text-white" onClick={()=>setCalculer(true)}>Calculer</button>{r&&<><button className="rounded-lg border px-4 py-3" onClick={()=>window.print()}>Imprimer / PDF</button><button className="rounded-lg border px-4 py-3" onClick={exporter}>Exporter l’échéancier CSV</button></>}</div>{resultat.erreur&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{resultat.erreur}</p>}
 {r&&<section aria-label="Résultat du prêt" className="space-y-5 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Échéances et coût</h2><div className="grid gap-4 md:grid-cols-3"><p className="rounded-xl bg-indigo-50 p-4">Mensualité hors assurance<br/><strong className="text-xl">{euros(r.mensualite)}</strong></p><p className="rounded-xl bg-indigo-50 p-4">Première échéance avec assurance<br/><strong className="text-xl">{euros(r.lignes[0].paiement)}</strong></p><p className="rounded-xl bg-indigo-50 p-4">Dernière échéance avec assurance<br/><strong className="text-xl">{euros(r.lignes[r.lignes.length-1].paiement)}</strong></p></div><p>Intérêts : {euros(r.interets)} ; assurance : {euros(r.assurance)} ; frais initiaux : {euros(Number(f.frais))}.</p><p className="text-lg font-semibold">Coût du financement hors capital : {euros(r.cout)}. Total capital et coûts : {euros(r.total)}.</p><p>Taux annuel effectif estimé sur les flux saisis : <strong>{r.tauxEffectif.toFixed(3)} %</strong>. Il correspond au TAEG estimatif seulement si tous les coûts obligatoires et leur calendrier sont correctement représentés. Cette approximation mensuelle ne constitue pas une vérification du TAEG contractuel ni du taux d’usure.</p><p className="text-sm text-slate-600">Échéances arrondies au centime ; dernière échéance ajustée pour solder exactement le capital. Assurance sur capital restant dû : mensualité totale décroissante. Hors différé, intérêts intercalaires, paliers, variation de prime, taux variable et remboursements anticipés.</p><button className="rounded-lg border px-4 py-3 print:hidden" onClick={()=>setTableau(!tableau)}>{tableau?'Masquer':'Afficher'} le tableau d’amortissement</button>{tableau&&<div className="max-h-[600px] overflow-auto print:max-h-none"><table className="w-full text-sm"><thead><tr className="text-left">{['Mois','Capital','Intérêts','Assurance','Paiement','Restant dû'].map(t=><th key={t} className="p-2">{t}</th>)}</tr></thead><tbody>{r.lignes.map(l=><tr key={l.mois} className="border-t"><td className="p-2">{l.mois}</td>{[l.capital,l.interets,l.assurance,l.paiement,l.restant].map((v,i)=><td className="p-2 whitespace-nowrap" key={i}>{euros(v)}</td>)}</tr>)}</tbody></table></div>}</section>}
 <section className="mt-8 space-y-4 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Comprendre les résultats</h2><p>La mensualité hors assurance utilise le taux nominal mensuel (taux annuel divisé par douze). À taux nul, le capital est réparti sur le nombre de mois. Le capital amorti augmente au fil du temps pour un prêt à échéances constantes ; il ne s’agit pas d’un amortissement constant.</p><p>Le TAEG ne se calcule pas en additionnant le taux du prêt, le taux d’assurance et un pourcentage de frais. Il rapproche les fonds reçus et tous les paiements obligatoires. Comparez le TAEG et le coût global des offres à garanties et hypothèses comparables ; aucun barème de taux de marché n’est présumé par cette page.</p><p>Le cadre HCSF prévoit en principe un taux d’effort de 35 %, assurance comprise, et une durée de 25 ans, avec des exceptions et une marge de flexibilité encadrées. Le respect de ces seuils ne garantit pas un accord de financement. Les pondérations des revenus et le reste à vivre sont appréciés par la banque.</p><p>En remboursement anticipé, les indemnités éventuellement prévues au contrat sont plafonnées au plus petit de six mois d’intérêts sur le capital remboursé au taux moyen du prêt et de 3 % du capital restant dû, sous réserve des cas légaux d’exonération. Un rachat doit comparer les échéances restantes et tous les frais ; aucun écart de taux ne garantit à lui seul sa rentabilité.</p><p>L’assurance peut être exigée par le prêteur. Son coût dépend des garanties, des quotités et du contrat ; une assurance externe n’est pas nécessairement calculée sur le capital restant dû.</p><ul className="list-disc space-y-2 pl-5"><li><a className="text-indigo-700 underline" href="https://www.banque-france.fr/fr/a-votre-service/particuliers/connaitre-pratiques-bancaires-assurance/credit/taux-usure">Banque de France : TAEG et taux d’usure</a></li><li><a className="text-indigo-700 underline" href="https://www.economie.gouv.fr/hcsf/mesures/mesure-relative-loctroi-de-credits-immobiliers">HCSF : conditions d’octroi des crédits immobiliers</a></li><li><a className="text-indigo-700 underline" href="https://www.service-public.gouv.fr/particuliers/vosdroits/F1669">Service Public : remboursement anticipé</a></li></ul></section>
 </div></MainLayout>;
}
