"use client";
import React,{useMemo,useState} from 'react';
import MainLayout from '@/components/MainLayout';
import {liquidationCessionPro,type CessionPro} from '@/lib/plusvalue-pro';
const euros=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
const initial={regime:'ir',nature:'amortissable',cession:'80000',acquisition:'100000',amortissements:'40000',frais:'0',detention:'6',activite:'6',secteur:'services',recettes:'100000',valeurEntreprise:'600000',exoneration:'aucune',confirme151:false,confirme238:false,retraite:false,confirmeRetraite:false,immobilierB:false,confirmeB:false,tmi:'30',cotisations:'',resultatIS:'0',isReduit:false,abattementTitres:false,confirmeTitres:false,soldeAbattementTitres:'500000',baremeTitres:false};
type Formulaire=typeof initial;
export default function PlusValuePro(){
 const [f,setF]=useState<Formulaire>(initial),[calculer,setCalculer]=useState(false),[methode,setMethode]=useState(false);
 const update=(k:keyof Formulaire,v:string|boolean)=>{setF(x=>({...x,[k]:v}));setCalculer(false);};
 const champ=(k:keyof Formulaire,label:string,aide?:string,max?:number)=><label key={k} className="block text-sm font-medium">{label}<input aria-label={label} type="number" min="0" max={max} step="any" value={String(f[k])} onChange={e=>update(k,e.target.value)} className="mt-2 w-full rounded-lg border bg-white p-3"/>{aide&&<span className="mt-1 block text-xs font-normal text-slate-600">{aide}</span>}</label>;
 const check=(k:keyof Formulaire,label:string)=><label className="flex gap-3 text-sm"><input type="checkbox" className="mt-1" checked={Boolean(f[k])} onChange={e=>update(k,e.target.checked)}/>{label}</label>;
 const resultat=useMemo(()=>{if(!calculer)return {r:null,erreur:''};try{
  for(const k of ['cession','acquisition','amortissements','frais','detention','activite','recettes','valeurEntreprise','resultatIS','soldeAbattementTitres'] as const)if(!f[k].trim())throw Error('Renseignez les montants et durées ; zéro est accepté.');
  const p={...f} as unknown as CessionPro;
  for(const k of ['cession','acquisition','amortissements','frais','detention','activite','recettes','valeurEntreprise','tmi','resultatIS','soldeAbattementTitres'] as const)p[k]=Number(f[k]);
  p.cotisations=f.cotisations.trim()?Number(f.cotisations):undefined;
  return {r:liquidationCessionPro(p),erreur:''};
 }catch(e){return {r:null,erreur:e instanceof Error?e.message:'Données invalides.'};}},[f,calculer]);
 const r=resultat.r;
 return <MainLayout><div className="mx-auto max-w-6xl px-4 py-10 text-slate-800"><h1 className="text-3xl font-bold">Plus-values professionnelles et cession de titres</h1><p className="mt-3">Estimation d’une cession en 2026. Choisissez d’abord le contribuable et le régime fiscal : la vente d’un actif par une société à l’IS et la vente de ses titres par un particulier suivent des calculs différents.</p><div className="my-6 flex gap-3 print:hidden"><button className={`rounded-lg px-4 py-3 ${!methode?'bg-indigo-700 text-white':'bg-slate-100'}`} onClick={()=>setMethode(false)}>Calculer une cession</button><button className={`rounded-lg px-4 py-3 ${methode?'bg-indigo-700 text-white':'bg-slate-100'}`} onClick={()=>setMethode(true)}>Conditions et sources</button></div>
 {!methode&&<><div className="grid gap-6 md:grid-cols-2"><section className="space-y-4 rounded-2xl border bg-slate-50 p-5"><h2 className="text-xl font-semibold">Opération</h2>
 <label className="block text-sm font-medium">Régime du cédant<select aria-label="Régime du cédant" value={f.regime} onChange={e=>{setF(x=>({...x,regime:e.target.value,exoneration:'aucune',retraite:false,immobilierB:false,abattementTitres:false}));setCalculer(false);}} className="mt-2 w-full rounded-lg border bg-white p-3"><option value="ir">Actif professionnel d’une activité à l’IR, dont LMP</option><option value="is">Actif vendu par une société à l’IS</option><option value="titres">Titres de société à l’IS vendus par un particulier</option></select></label>
 {f.regime!=='titres'&&<label className="block text-sm font-medium">Nature de l’actif<select aria-label="Nature de l’actif" className="mt-2 w-full rounded-lg border bg-white p-3" value={f.nature} onChange={e=>{update('nature',e.target.value);setF(x=>({...x,immobilierB:false,retraite:false,exoneration:'aucune'}));}}><option value="amortissable">Actif amortissable hors immobilier</option><option value="non_amortissable">Actif non amortissable hors immobilier</option><option value="immeuble">Immeuble professionnel, dont location LMP</option></select></label>}
 {champ('cession','Prix de cession de cet actif ou de ces titres (€)')}{champ('acquisition','Prix de revient fiscal (€)','Valeur fiscale avant amortissements, frais capitalisés inclus si admissibles. Pour les titres : prix de revient corrigé selon le dossier.')}
 {f.regime!=='titres'&&f.nature!=='non_amortissable'&&champ('amortissements','Amortissements fiscaux cumulés (€)','Amortissements de cet actif retenus pour sa VNC, issus du bilan ; pas ceux d’autres biens ni du mobilier vendu séparément.')}
 {champ('frais','Frais de cession déductibles (€)')}{champ('detention','Durée révolue de détention (années)','Durée de cet actif : ne pas confondre avec la durée d’activité. Pour l’immobilier B, seules les années entières d’affectation éligible sont retenues.')}
 {f.regime!=='titres'&&champ('activite','Durée d’activité professionnelle (années)','Périodes fiscalement éligibles effectivement accomplies. Les années LMNP ne constituent pas automatiquement des années d’activité LMP.')}
 {f.regime!=='is'&&champ('tmi','Taux marginal d’imposition (%)','IR approximé à TMI constant ; hors décote, contributions sur hauts revenus et déductions sociales induites.',45)}
 {f.regime==='ir'&&champ('cotisations','Cotisations supplémentaires liées à cette cession (€)','Estimation Urssaf/comptable selon le régime social et les exonérations retenues. Zéro accepté ; laisser vide produit un total provisoire hors ces cotisations. Une exonération fiscale CT ne les annule pas automatiquement.')}
 {f.regime==='is'&&<>{champ('resultatIS','Autre bénéfice fiscal positif de l’exercice (€)','Permet d’utiliser seulement la fraction encore disponible de la tranche à 15 %. Hors déficits reportables et résultat négatif.')}{check('isReduit','La société remplit les conditions du taux IS réduit : CA ≤10 M€, capital entièrement libéré et détention éligible d’au moins 75 %. Exercice de douze mois.')}</>}
 </section><section className="space-y-4 rounded-2xl border bg-slate-50 p-5"><h2 className="text-xl font-semibold">Dispositifs à appliquer</h2><p className="text-sm">Les conditions doivent être vérifiées sur les actes et la situation réelle. Un petit prix ou un départ à la retraite ne suffit pas à lui seul.</p>
 {f.regime!=='titres'?<><label className="block text-sm">Exonération générale<select aria-label="Exonération générale" className="mt-2 w-full rounded-lg border bg-white p-3" value={f.exoneration} onChange={e=>update('exoneration',e.target.value)}><option value="aucune">Aucune</option>{f.regime==='ir'&&<option value="151">Article 151 septies — recettes de l’activité</option>}{f.nature!=='immeuble'&&<option value="238">Article 238 quindecies — transmission éligible</option>}</select></label>
 {f.exoneration==='151'&&<><label className="block text-sm">Catégorie de recettes<select aria-label="Catégorie de recettes" className="mt-2 w-full rounded-lg border bg-white p-3" value={f.secteur} onChange={e=>update('secteur',e.target.value)}><option value="services">Services, BNC ou location meublée professionnelle</option><option value="ventes">Ventes et fourniture de logement hors location meublée</option></select></label>{champ('recettes','Moyenne des recettes de référence HT (€)','Moyenne des deux années de référence définies par CGI 151 septies, annualisées si nécessaire ; activités et participations à agréger selon le texte.')}{check('confirme151','Je confirme une activité à titre professionnel pendant au moins cinq ans, une opération et un actif éligibles, sans terrain à bâtir exclu, activité agricole ou mixte nécessitant d’autres seuils, ni report incompatible.')}</>}
 {f.exoneration==='238'&&<>{champ('valeurEntreprise','Valeur totale transmise pour le seuil 238 quindecies (€)','Valeur de l’entreprise ou branche pour le dispositif, hors immobilier, avec les charges en capital et indemnités pertinentes ; distincte du prix de l’actif calculé ici.')}{check('confirme238','Je confirme la transmission d’une entreprise, branche complète ou droits professionnels assimilés, l’activité ≥5 ans, les conditions d’indépendance du cessionnaire et leur maintien, ainsi que les conditions PME/capital et aides applicables si le cédant est à l’IS. Pas de report incompatible, ni seuil agricole spécial.')}</>}
 {f.regime==='ir'&&f.nature==='immeuble'&&<>{check('immobilierB','Appliquer l’abattement immobilier de l’article 151 septies B')}{f.immobilierB&&check('confirmeB','Je confirme l’affectation éligible à l’exploitation sur la durée saisie, la nature immobilière admise et l’absence de terrain à bâtir exclu. Une location meublée professionnelle peut être éligible.')}</>}
 {f.regime==='ir'&&f.nature!=='immeuble'&&<>{check('retraite','Appliquer l’exonération retraite de l’article 151 septies A')}{f.retraite&&check('confirmeRetraite','Je confirme toutes les conditions : cession à titre onéreux de l’entreprise ou intégralité des droits professionnels éligibles, activité ≥5 ans, PME et capital éligibles, cessation de toute fonction et liquidation de retraite dans les deux ans avant/après, absence de contrôle prohibé du repreneur et maintien des conditions. Hors immobilier et cas agricoles spéciaux.')}</>}
 </>:<>{check('baremeTitres','Simuler l’option globale pour le barème au TMI saisi (hors abattements historiques de durée et hors CSG déductible).')}{check('abattementTitres','Appliquer l’abattement du dirigeant partant à la retraite — CGI 150-0 D ter')}{f.abattementTitres&&<>{champ('soldeAbattementTitres','Solde d’abattement fixe disponible (€)','Plafond ordinaire de 500 000 € par société, après les fractions déjà utilisées ; ne se renouvelle pas à chaque vente.',500000)}{check('confirmeTitres','Je confirme les conditions complètes : titres détenus ≥2 ans ; fonctions de direction éligibles, effectives, normalement rémunérées et représentant la part requise des revenus professionnels (plus de 50 %), et participation d’au moins 25 % pendant les cinq ans précédents ; quotité cédée exigée ; cessation des fonctions et retraite dans les deux ans ; PME, activité, siège et IS éligibles ; absence de participation interdite dans l’acquéreur. Hors dispositif agricole spécial.')}</>}</>}
 <p className="text-sm text-slate-600">Un actif de nature et durée homogènes par calcul. Une cession d’entreprise comportant plusieurs actifs doit être ventilée puis faire l’objet de la compensation fiscale des plus et moins-values. Cette page ne liquide pas les reports, moins-values antérieures, étalements, apports, démembrements ou régimes agricoles particuliers.</p></section></div>
 <div className="my-6 flex flex-wrap gap-3 print:hidden"><button onClick={()=>setCalculer(true)} className="rounded-lg bg-indigo-700 px-5 py-3 font-semibold text-white">Calculer</button>{r&&<button onClick={()=>window.print()} className="rounded-lg border px-5 py-3">Imprimer / PDF</button>}</div>{resultat.erreur&&<p role="alert" className="my-4 rounded-lg bg-red-50 p-4 text-red-800">{resultat.erreur}</p>}
 {r&&<section aria-label="Résultat de cession" className="space-y-4 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Estimation de la cession</h2><p>Valeur nette fiscale : {euros(r.vnc)} ; {r.gain<0?'moins-value':'plus-value'} : <strong>{euros(r.gain)}</strong>.</p>{r.gain<0&&<p>La moins-value n’engendre aucun remboursement calculé ici. Sa qualification et son imputation dépendent du régime, de l’actif et de la compensation avec les autres résultats.</p>}{f.regime==='ir'&&<p>Plus-value à court terme : {euros(r.courtTerme)} ; à long terme : {euros(r.longTerme)}.</p>}<p>Dispositifs appliqués : {r.dispositifs.length?r.dispositifs.join(' ; '):'aucun'}.</p><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{[['Impôt sur le revenu',r.ir],['Prélèvements sociaux',r.social],['Supplément d’impôt sur les sociétés',r.impotSociete],['Cotisations sociales saisies',r.cotisations]].map(([label,m])=><tr className="border-b" key={String(label)}><th className="p-3 text-left font-normal">{label}</th><td className="p-3 text-right">{euros(Number(m))}</td></tr>)}</tbody></table></div>{r.cotisationsManquantes&&<p className="rounded-lg bg-amber-50 p-3 font-semibold">Cotisations CT non renseignées : total et net ci-dessous provisoires, hors cotisations supplémentaires éventuelles, y compris en cas d’exonération fiscale.</p>}<p className="text-lg font-semibold">Total {r.cotisationsManquantes?'hors cotisations CT':''} : {euros(r.total)} — net estimé : {euros(r.net)}</p><p className="text-sm text-slate-600">Net après frais saisis et fiscalité estimée, avant dettes à rembourser. {f.regime==='is'?'Somme conservée dans la société : fiscalité d’une distribution ultérieure aux associés non comprise.':'Hors contributions éventuelles sur hauts revenus et effet sur les autres revenus du foyer.'}</p></section>}
 </>}
 {methode&&<section className="space-y-5 rounded-2xl border p-5"><h2 className="text-xl font-semibold">Méthode et limites — règles 2026</h2><p>Pour un actif professionnel, la plus-value est le prix de cession net de frais moins la valeur nette fiscale. À l’IR, une détention inférieure à deux ans entraîne du court terme ; après deux ans, la reprise d’amortissements reste à court terme et le surplus relève du long terme. Un prix de vente inférieur au prix d’achat peut donc produire une plus-value si l’actif a été amorti.</p><p>La plus-value professionnelle nette à long terme relève du taux d’IR de 12,8 %, auquel s’ajoutent les prélèvements sociaux de 18,6 % en 2026, sous réserve des exonérations applicables. Elle ne bénéficie pas de l’option globale 2OP propre aux revenus mobiliers. Le court terme s’ajoute au résultat ordinaire et peut supporter des cotisations même si son impôt est exonéré : leur montant est demandé séparément.</p><p>Les exonérations 151 septies (recettes) et 238 quindecies (transmission) ne se cumulent pas sur une même plus-value. Les dispositifs compatibles sont appliqués dans l’ordre : abattement immobilier 151 septies B, exonération IR retraite 151 septies A, puis l’un des deux dispositifs généraux. Les exonérations A et 238 ne couvrent pas les plus-values immobilières. B ne porte que sur le long terme, à raison de 10 % par année entière éligible au-delà de cinq ans.</p><p>Pour une société à l’IS, le calcul estime le supplément d’IS au taux ordinaire, ou à 15 % sur la tranche encore disponible de 42 500 € puis 25 %. Ce calcul suppose un exercice de douze mois et un bénéfice antérieur positif sans déficits reportables. Les actifs soumis à un régime particulier, notamment titres de participation, ne relèvent pas de cette estimation.</p><p>Pour les titres détenus dans le patrimoine privé, aucun découpage CT/LT professionnel n’est appliqué. L’abattement retraite de 500 000 € réduit uniquement l’IR, pas les prélèvements sociaux. Le barème est une option globale à examiner sur tous les revenus concernés ; ce calcul au TMI n’en mesure pas l’effet complet et n’intègre pas les abattements de durée éventuellement applicables aux titres acquis avant 2018. Les titres professionnels d’une société de personnes à l’IR demandent une analyse distincte.</p><ul className="list-disc space-y-2 pl-5">
 <li><a className="text-indigo-700 underline" href="https://entreprendre.service-public.gouv.fr/vosdroits/F33162">Service Public : imposition des plus-values professionnelles</a></li>
 <li><a className="text-indigo-700 underline" href="https://www.impots.gouv.fr/professionnel/questions/comment-beneficier-de-lexoneration-des-plus-values-reservees-aux-petites">DGFiP : exonération des petites entreprises</a></li>
 <li><a className="text-indigo-700 underline" href="https://www.impots.gouv.fr/professionnel/questions/ai-je-droit-une-exoneration-en-cas-de-plus-value">DGFiP : dispositifs d’exonération</a></li>
 <li><a className="text-indigo-700 underline" href="https://bofip.impots.gouv.fr/bofip/6156-PGP.html/identifiant=BOI-BIC-PVMV-40-20-50-20250723">BOFiP : 238 quindecies et cumuls</a></li>
 <li><a className="text-indigo-700 underline" href="https://bofip.impots.gouv.fr/bofip/6230-PGP.html/identifiant=BOI-BIC-PVMV-40-10-10-30-20220622">BOFiP : effets et ordre des exonérations</a></li>
 <li><a className="text-indigo-700 underline" href="https://bofip.impots.gouv.fr/bofip/11406-PGP.html/identifiant=BOI-RPPM-PVBMI-20-40-10-40-20241114">BOFiP : conditions du dirigeant partant à la retraite</a></li>
 <li><a className="text-indigo-700 underline" href="https://bofip.impots.gouv.fr/bofip/3610-PGP.html/identifiant=BOI-BIC-CHAMP-40-20-20260819">BOFiP : cession d’immeubles en location meublée professionnelle</a></li>
 </ul></section>}
 </div></MainLayout>;
}
