"use client";

import React, { useMemo, useState } from 'react';
import MainLayout from '@/components/MainLayout';
import { PASS_2026, pointsAnnuelsAgircArrco, projectionRetraite, type ProjectionRetraite } from '@/lib/retraite';

const euros=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
const age=(n:number)=>`${Math.floor(n)} ans${Math.round((n%1)*12)?` et ${Math.round((n%1)*12)} mois`:''}`;
const initial={naissance:'1975-06-15',statut:'salarie',objectif:'plein',trimestres:'',trimestresRegime:'',trimestresFutursAn:'4',rachatTauxSeul:'0',surcoteAcquise:'0',reference:'',points:'',pointsFutursAn:'',salaire:'42000',complement:'',socialBase:'9.1',socialComplement:'10.1',revenuNet:''};
type Formulaire=typeof initial;

export default function RetraitePage(){
  const [form,setForm]=useState<Formulaire>(initial);
  const [tab,setTab]=useState('estimation');
  const [calculer,setCalculer]=useState(false);
  const update=(key:keyof Formulaire,value:string)=>{setForm(f=>({...f,[key]:value}));};
  const resultat=useMemo(()=>{
    if(!calculer)return {scenarios:[],erreur:''};
    try{
      for(const key of ['trimestres','trimestresRegime','reference'] as const)if(form[key].trim()==='')throw Error('Renseignez les durées et le revenu de référence issus de votre relevé.');
      if(form.statut==='salarie'&&!form.points.trim()&&!form.complement.trim())throw Error('Renseignez vos points Agirc-Arrco ou une pension complémentaire du relevé (zéro accepté).');
      if(form.statut!=='salarie'&&!form.complement.trim())throw Error('Renseignez la complémentaire annuelle de votre caisse (zéro si aucun droit).');
      const p:ProjectionRetraite={naissance:form.naissance,statut:form.statut as ProjectionRetraite['statut'],objectif:form.objectif as ProjectionRetraite['objectif'],trimestres:Number(form.trimestres),trimestresRegime:Number(form.trimestresRegime),trimestresFutursAn:Number(form.trimestresFutursAn),rachatTauxSeul:Number(form.rachatTauxSeul),surcoteAcquise:Number(form.surcoteAcquise),reference:Number(form.reference),points:Number(form.points),pointsFutursAn:form.pointsFutursAn.trim()?Number(form.pointsFutursAn):form.statut==='salarie'&&Number(form.trimestresFutursAn)>0?pointsAnnuelsAgircArrco(Math.max(0,Number(form.salaire))):0,complement:Number(form.complement),complementSaisi:!!form.complement.trim(),socialBase:Number(form.socialBase),socialComplement:Number(form.socialComplement),revenuNet:Number(form.revenuNet)};
      return {scenarios:[0,24,48].map(m=>projectionRetraite(p,new Date(),m)),erreur:''};
    }catch(e){return {scenarios:[],erreur:e instanceof Error?e.message:'Vérifiez les données saisies.'};}
  },[form,calculer]);
  const r=resultat.scenarios[0];
  const champ=(key:keyof Formulaire,label:string,aide?:string,max?:number)=><label className="block text-sm font-medium" key={key}>{label}<input className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3" type="number" min="0" max={max} step="any" value={form[key]} onChange={e=>update(key,e.target.value)}/>{aide&&<span className="mt-1 block text-xs font-normal text-slate-600">{aide}</span>}</label>;
  return <MainLayout><div className="mx-auto max-w-6xl px-4 py-10 text-slate-800">
    <h1 className="text-3xl font-bold">Simulateur retraite</h1>
    <p className="mt-3 max-w-4xl">Comparez des dates de départ à partir de vos droits connus. Règles des départs à compter du 1er septembre 2026, paramètres monétaires 2026 constants. Le salaire actuel ne permet pas de reconstituer vos droits passés : utilisez votre relevé Info Retraite.</p>
    <nav className="my-6 flex flex-wrap gap-2 print:hidden" aria-label="Sections retraite">{[['estimation','Estimation et comparaison'],['methode','Calculs et sources']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-4 py-3 ${tab===id?'bg-indigo-700 text-white':'bg-slate-100'}`}>{label}</button>)}</nav>
    {tab==='estimation'?<>
      <section className="grid gap-6 md:grid-cols-2">
        <div className="space-y-4 rounded-2xl border bg-slate-50 p-5">
          <h2 className="text-xl font-semibold">Carrière et départ</h2>
          <label className="block text-sm font-medium">Date de naissance<input type="date" min="1950-01-01" max="2008-12-31" className="mt-2 block w-full rounded-lg border p-3" value={form.naissance} onChange={e=>update('naissance',e.target.value)}/></label>
          <label className="block text-sm font-medium">Régime simulé<select className="mt-2 block w-full rounded-lg border p-3" value={form.statut} onChange={e=>{const statut=e.target.value;setForm(f=>({...f,statut,reference:'',complement:'',socialComplement:statut==='salarie'?'10.1':'9.1'}));}}><option value="salarie">Salarié privé — Assurance retraite et Agirc-Arrco</option><option value="independant">Artisan/commerçant — régime aligné et RCI</option><option value="fonctionnaire">Fonctionnaire sédentaire — SRE/CNRACL</option><option value="liberal">Profession libérale — montants de la caisse</option></select></label>
          {champ('trimestres','Trimestres validés tous régimes à ce jour','Inclure les périodes assimilées et majorations déjà reconnues. Aucun ajout automatique pour enfants, chômage ou maladie.')}
          {champ('trimestresRegime',form.statut==='fonctionnaire'?'Trimestres liquidables SRE/CNRACL à ce jour':'Trimestres retenus dans le régime de base simulé','Distinguer la durée tous régimes (taux) de celle servant à proratiser cette pension. En libéral, champ sans effet sur le montant saisi.')}
          {champ('trimestresFutursAn','Trimestres cotisés projetés par année','De 0 à 4, sous réserve de revenus suffisants. Projection régulière simplifiée, hors règles de validation de l’année de liquidation.',4)}
          {champ('rachatTauxSeul','Rachats option taux seul, non inclus ci-dessus','Améliorent le taux sans augmenter la durée de proratisation. Les rachats taux + durée doivent déjà figurer dans les durées saisies.')}
          {champ('surcoteAcquise','Trimestres de surcote déjà acquis et confirmés','Uniquement ceux acquis après l’âge légal et la durée requise ; aucun calcul rétroactif automatique.')}
          <label className="block text-sm font-medium">Objectif de départ<select className="mt-2 block w-full rounded-lg border p-3" value={form.objectif} onChange={e=>update('objectif',e.target.value)}><option value="legal">Premier départ légal possible à venir</option><option value="plein">Premier départ projeté sans décote</option><option value="surcote">Deux ans après ce départ sans décote</option></select></label>
        </div>
        <div className="space-y-4 rounded-2xl border bg-slate-50 p-5">
          <h2 className="text-xl font-semibold">Montants issus du relevé</h2>
          {champ('reference',form.statut==='fonctionnaire'?'Traitement indiciaire brut annuel de référence (€)':form.statut==='liberal'?'Pension de base brute annuelle estimée par la caisse (€)':'Revenu annuel moyen revalorisé retenu par la caisse (€)',form.statut==='fonctionnaire'?'Traitement détenu depuis six mois, hors primes ; pas le salaire brut total.':form.statut==='liberal'?'Montant à la date choisie. Conservé à l’identique dans les comparaisons : demander une estimation distincte pour chaque date.':'SAM/RAM des meilleures années. Maintenu constant dans les scénarios ; le simulateur ne reconstruit ni salaires historiques ni coefficients de revalorisation.')}
          {form.statut==='salarie'&&<>{champ('points','Points Agirc-Arrco déjà acquis','Points unifiés du relevé, hors ancienne tranche C avant 2016 nécessitant un traitement distinct.')}{champ('salaire','Salaire brut annuel futur (€)','Sert seulement aux points futurs : taux d’acquisition 6,2 % / 17 %, PASS et prix du point 2026. Salaire et paramètres constants.')}{champ('pointsFutursAn','Points Agirc-Arrco futurs par an — facultatif','Prioritaire sur l’estimation par salaire ; saisir 0 si aucun point nouveau. Ne se déduit pas du nombre de trimestres.')}</>}
          {champ('complement','Pension complémentaire brute annuelle du relevé (€)',form.statut==='salarie'?'Facultatif si points renseignés. Montant final après minoration : prioritaire sur les points, conservé dans les trois scénarios.':'RCI, caisse libérale ou rente RAFP à saisir, sans pourcentage forfaitaire. Montant conservé dans les trois scénarios. Un capital RAFP ne doit pas être saisi comme rente annuelle.')}
          {champ('socialBase','Prélèvements sociaux sur la base (%)','Métropole : 9,1 % normal ; 7,4 % médian ; 4,3 % réduit ; 0 % exonéré. Dépend du RFR et des parts, à confirmer sur notification.',100)}
          {champ('socialComplement','Prélèvements sociaux sur la complémentaire (%)','Agirc-Arrco : assurance maladie de 1 % en plus aux taux normal/médian, sauf exonération. Règles particulières de résidence à vérifier.',100)}
          {champ('revenuNet','Revenu professionnel net annuel avant IR (€) — facultatif','Permet le taux de remplacement. Aucun coefficient brut/net arbitraire n’est appliqué.')}
        </div>
      </section>
      <p className="my-5 rounded-lg bg-amber-50 p-4 text-sm">Projection du régime sélectionné : les pensions d’autres régimes ne sont pas ajoutées. Minimum contributif/garanti, majorations pour enfants, bonifications, catégories actives, carrières longues, handicap et départs anticipés ne sont pas liquidés ici. En libéral, seuls les montants de caisse saisis sont repris. Les dates restent à confirmer par la caisse.</p>
      <button onClick={()=>setCalculer(true)} className="rounded-lg bg-indigo-700 px-6 py-3 font-semibold text-white print:hidden">Calculer la retraite</button>
      {resultat.erreur&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">{resultat.erreur}</p>}
      {r&&<section aria-label="Résultats retraite" className="mt-8 space-y-5">
        <div className="rounded-2xl bg-indigo-50 p-6"><h2 className="text-2xl font-bold">{euros(r.net/12)} nets par mois avant impôt</h2><p className="mt-2">Départ projeté : {new Date(r.date+'T00:00:00Z').toLocaleDateString('fr-FR',{timeZone:'UTC'})} — {age(r.age)}.</p><p>Âge légal : {age(r.regle.ans+r.regle.mois/12)} ; durée requise : {r.regle.trimestres} trimestres. Sans décote projeté à {age(r.agePlein)} ; une pension peut rester proratisée à cet âge.</p></div>
        <div className="grid gap-4 sm:grid-cols-3">{[['Base brute / mois',euros(r.base/12)],['Complémentaire brute / mois',euros(r.complement/12)],['Taux de remplacement',r.remplacement===null?'Revenu net non renseigné':r.remplacement.toFixed(1)+' %']].map(([a,b])=><div className="rounded-xl border p-4" key={a}><p>{a}</p><p className="mt-2 text-xl font-semibold">{b}</p></div>)}</div>
        <p className="text-sm">Prélèvements sociaux annuels : {euros(r.brut-r.net)}. {form.statut!=='liberal'&&<>Durée projetée tous régimes : {r.total} trimestres ; proratisation de la base : {(r.ratio*100).toFixed(2)} % ; décote : {r.decote} trimestres ; surcote retenue : {r.surcote} trimestres.</>} {form.statut==='salarie'&&!form.complement.trim()&&<>Points : {r.points.toFixed(2)} ; coefficient de minoration définitive Agirc-Arrco : {r.coefficient.toFixed(4)}.</>}</p>
        <h2 className="text-xl font-semibold">Comparer les départs</h2>
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Départ','Net / mois avant IR','Base brute / an','Complémentaire / an','Cumul net jusqu’à 85 ans'].map(h=><th className="border-b p-3" key={h}>{h}</th>)}</tr></thead><tbody>{resultat.scenarios.map((s,i)=><tr key={s.date}><th className="border-b p-3">{i===0?'Choisi':`+${i*2} ans`}<span className="block font-normal">{s.date}</span></th><td className="border-b p-3">{euros(s.net/12)}</td><td className="border-b p-3">{euros(s.base)}</td><td className="border-b p-3">{euros(s.complement)}</td><td className="border-b p-3">{euros(s.cumul85)}</td></tr>)}</tbody></table></div>
        <p className="text-sm">Cumul arithmétique non actualisé, sans revalorisation ni impôt, hors rémunération pendant le report et sans hypothèse de survie. Les pensions de caisse saisies restent fixes : cette comparaison ne prédit pas leur évolution selon l’âge. Les résultats se recalculent à chaque modification.</p>
        <button onClick={()=>window.print()} className="rounded-lg border px-4 py-3 print:hidden">Imprimer / enregistrer en PDF</button>
      </section>}
    </>:<section className="max-w-4xl space-y-6">
      <h2 className="text-2xl font-semibold">Règles et limites du calcul</h2>
      <p>Le calendrier tient compte de la loi de financement de la Sécurité sociale pour 2026 : 1963, 1964 et janvier–mars 1965 : 62 ans 9 mois et 170 trimestres ; avril–décembre 1965 : 63 ans et 171 ; 1966 : 63 ans 3 mois ; 1967 : 63 ans 6 mois ; 1968 : 63 ans 9 mois ; 1969 et après : 64 ans, ces dernières générations avec 172 trimestres. Les personnes nées de septembre à décembre 1961 ont besoin de 169 trimestres. <a className="underline" href="https://www.service-public.gouv.fr/particuliers/actualites/A18825">Calendrier officiel</a>.</p>
      <p>La base privée utilise le revenu annuel moyen, le taux de 50 % et la durée dans le régime divisée par la durée requise. La décote retient le plus petit nombre de trimestres manquant à la durée requise ou à 67 ans, limité à 20. Quatre trimestres réduisent le taux de 50 % à 47,5 %, pas à 45 %. La surcote de huit trimestres admissibles majore la pension de 10 %. Plafond ordinaire avant majorations : {euros(PASS_2026/2)} par an en 2026. <a className="underline" href="https://www.service-public.gouv.fr/particuliers/vosdroits/F14044">Taux plein et proratisation</a>.</p>
      <p>Pour un fonctionnaire sédentaire, la base de départ est le traitement indiciaire annuel détenu depuis six mois × 75 % × la durée liquidable / la durée requise. Décote et surcote sont ensuite appliquées. Les primes et la RAFP sont distinctes. Pour une profession libérale, les régimes à points et complémentaires varient : la formule privée n’est pas appliquée. <a className="underline" href="https://www.service-public.gouv.fr/particuliers/vosdroits/F21142">Montant de la retraite de l’agent public</a>.</p>
      <p>Agirc-Arrco : les points futurs estimés utilisent les taux d’acquisition de 6,2 % sous le PASS et 17 % entre un et huit PASS, divisés par 20,1877 €. Le taux d’appel de 127 % et les contributions d’équilibre ne génèrent pas de points. La valeur de service retenue est 1,4386 €. La minoration définitive pour départ sans taux plein est distincte de l’ancien malus temporaire supprimé. <a className="underline" href="https://www.agirc-arrco.fr/particuliers/ma-retraite/comprendre-ma-retraite/points-de-retraite-comment-sont-ils-obtenus/">Acquisition des points</a> ; <a className="underline" href="https://www.agirc-arrco.fr/storage/2024/10/Coefficients-de-minorations-AA.pdf">Coefficients officiels septembre 2026</a>.</p>
      <p>Le net est calculé avant impôt sur le revenu avec les deux taux sociaux saisis. Le taux CSG dépend notamment du RFR, des parts et des règles de franchissement des seuils ; le simulateur ne le détermine pas. La cotisation maladie Agirc-Arrco peut s’ajouter. L’abattement IR des pensions déclarées en 2026 est de 10 %, avec minimum 454 € par pensionné et plafond 4 439 € par foyer ; il ne réduit pas l’assiette sociale utilisée ici. <a className="underline" href="https://www.agirc-arrco.fr/particuliers/ma-retraite/vivre-ma-retraite/prelevements-sociaux/">Prélèvements complémentaires</a> ; <a className="underline" href="https://www.service-public.gouv.fr/particuliers/vosdroits/F415">Déclaration des pensions</a>.</p>
      <p>Les rachats ne sont pas tous équivalents : l’option taux seul ne crée pas de durée de proratisation. La retraite progressive est accessible dès 60 ans depuis septembre 2025 sous conditions, dont 150 trimestres. Ces opérations et le cumul emploi-retraite nécessitent une étude distincte. Aucun rachat ni produit d’épargne n’est recommandé automatiquement. <a className="underline" href="https://www.service-public.gouv.fr/particuliers/vosdroits/F12842">Retraite progressive</a>.</p>
      <a className="inline-block rounded-lg bg-indigo-700 px-4 py-3 text-white" href="https://www.info-retraite.fr/">Consulter mon relevé et les estimations des caisses</a>
    </section>}
  </div></MainLayout>;
}
