import MainLayout from '@/components/MainLayout';
import Link from 'next/link';
export default function MethodologieFiscale() {
  return <MainLayout><article className="max-w-3xl mx-auto px-6 py-12 space-y-6 text-gray-800">
    <h1 className="text-3xl font-bold">Calculs et références fiscales</h1>
    <p>Revue du 14 septembre 2026 : calculs, assiettes et contenus des simulateurs listés ci-dessous, avec tests de cas chiffrés et contrôles dans le navigateur. Cette revue ne constitue pas une certification juridique ni une couverture de toutes les situations particulières. L’impôt sur le revenu utilise le barème 2026 applicable aux revenus 2025. Les projections supposent ces règles constantes.</p>
    <h2 className="text-xl font-semibold">Extensions et contrôles de septembre 2026</h2>
    <p>Le mode foyer, facultatif en LMNP, foncier, SCI et Relance logement, estime la variation d’IR avant/après avec quotient familial ordinaire plafonné et décote. Les situations particulières, réductions, crédits et contributions sur hauts revenus restent hors périmètre. En SCI, ce mode suppose zéro intérêt de compte courant et une distribution au PFU. La SCI annuelle ne calcule pas l’économie d’un déficit global ; le module foncier le fait.</p>
    <p>La capacité d’emprunt inclut l’assurance dans la mensualité disponible et retranche les frais du budget. Le seuil usuel de 35 % est une hypothèse modifiable ; aucune acceptation bancaire n’est prédite. La comparaison achat/location/revente suit le capital remboursé, les déficits, l’impôt de cession, les avances en compte courant et le dividende final. Elle distingue l’argent personnel du solde conservé en SCI et conserve la fiscalité 2026 sur tout l’horizon.</p>
    <p>Relance logement : acquisitions du 21 février 2026 au 31 décembre 2028, location nue en collectif. Le modèle traite le neuf/VEFA et l’ancien avec réhabilitation lourde à 30 % minimum ; il ne qualifie pas automatiquement les autres travaux assimilant un immeuble au neuf. Base hors foncier, prorata mensuel, plafond partagé du foyer et cumul d’amortissement sont contrôlés. Plafond de déficit global ordinaire de 10 700 € ; majoration énergétique, reports antérieurs et revente à calculer séparément. Les conditions de location et plafonds locaux doivent être vérifiés avec les pièces.</p>
    <p>Les tests couvrent des exemples chiffrés et cas limites, dont le plafonnement IFI sans impôt négatif, les changements de tranche du foyer, la capacité de financement et les flux de sortie SCI. Les <Link className="underline" href="/guides">12 guides</Link> donnent des hypothèses, pièces et références pour reproduire les exemples. Ces contrôles ne valent pas certification de toutes les situations fiscales.</p>
    <h2 className="text-xl font-semibold">Sources</h2>
    <ul className="list-disc pl-6 space-y-2">
      <li><a className="underline" href="https://www.legifrance.gouv.fr/codes/id/LEGISCTA000032132058">Code de commerce : tarifs des notaires</a></li>
      <li><a className="underline" href="https://www.impots.gouv.fr/droits-denregistrement">DGFiP : DMTO, tableau au 1er juin 2026</a></li>
      <li><a className="underline" href="https://www.impots.gouv.fr/particulier/calcul-et-paiement-des-droits">DGFiP : donations et barèmes</a></li>
      <li><a className="underline" href="https://www.impots.gouv.fr/particulier/plus-values-imposees">DGFiP : plus-values immobilières</a></li>
      <li><a className="underline" href="https://www.impots.gouv.fr/particulier/calcul-de-lifi">DGFiP : IFI</a></li>
      <li><a className="underline" href="https://bofip.impots.gouv.fr/bofip/2494-PGP.html/identifiant=BOI-IR-LIQ-20-20-20-20260407">BOFiP : plafonnement du quotient familial</a></li>
      <li><a className="underline" href="https://bofip.impots.gouv.fr/bofip/2495-PGP.html/identifiant=BOI-IR-LIQ-20-20-30-20260407">BOFiP : décote</a></li>
      <li><a className="underline" href="https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000053154357/2026-09-01">CGI article 31 : amortissement du bailleur privé</a></li>
      <li><a className="underline" href="https://www.service-public.gouv.fr/particuliers/vosdroits/F39735">Service Public : Relance logement, conditions et plafonds</a></li>
      <li><a className="underline" href="https://www.economie.gouv.fr/hcsf/mesures/mesure-relative-loctroi-de-credits-immobiliers">HCSF : règles du crédit immobilier</a></li>
    </ul>
    <h2 className="text-xl font-semibold">Hypothèses à vérifier pour votre simulation</h2>
    <p>Le calcul des droits de succession est désormais distinct et accessible depuis le module donation. Les parts nettes civiles sont renseignées par héritier ; les frais des actes notariaux restent accessibles dans la prétaxe. Donation : un donateur et un bénéficiaire sélectionné à la fois. Les exonérations de dons d’argent supposent leurs plafonds disponibles et les conditions confirmées. La réduction Dutreil de 50 % sur les droits de la fraction éligible en pleine propriété avant 70 ans est comprise si l’âge et les conditions sont renseignés.</p>
    <p>SCI : comparaison annuelle en location nue au réel, pour des associés personnes physiques résidents relevant de la même TMI. Résultat, amortissement, trésorerie et distribution sont distincts. La revente IS utilise la valeur comptable renseignée ; l’impôt d’une distribution ultérieure du produit de vente n’est pas inclus. Transmission et IFI sont traités dans leurs modules propres.</p>
    <p>Prétaxe : les formalités et débours dépendent du dossier. Le neuf utilise une assiette hors TVA immobilière. Les réductions départementales conditionnelles et tarifs locaux nécessitent un contrôle du dossier. Le bail à construction utilise trois assiettes d’émoluments et une assiette CSI distincte. Les actes de sociétés peuvent nécessiter des droits complémentaires selon la nature des apports.</p>
    <p>IFI : plafonnement pour les résidents fiscaux français, avec revenus mondiaux et impôts de l’année précédente. Prêts in fine ou familiaux, exceptions à la limitation des dettes et déduction de l’IFI lui-même ne sont pas automatisés.</p>
    <p>Viager : scénarios financiers à horizon choisi ou coefficient actuariel fourni par votre professionnel, sans table de mortalité intégrée. La fraction imposable de la rente est séparée de sa tarification.</p>
    <p>Holding : SCI et mère IS distinctes, remboursements du capital compris dans la trésorerie, quote-part mère-fille après frais, distributions plafonnées. La comparaison n’inclut pas la fiscalité de revente. Statuts : modèles sociaux Urssaf publiés en juillet 2026, avec les hypothèses de foyer et d’activité précisées dans le module.</p>
    <p>Retraite : relevés de carrière requis, durées tous régimes et durée liquidable distinctes, calendrier de septembre 2026, prélèvements base et complémentaire séparés. Les montants des caisses libérales et complémentaires non Agirc-Arrco sont saisis ; aucune pension forfaitaire n’est reconstruite. Les projections gardent les paramètres monétaires 2026 constants.</p>
    <p>Plus-values immobilières : prix et frais sur une même quote-part ; droits démembrés valorisés d’après les actes, durée de date à date et exonérations sous conditions. Plus-values professionnelles : les branches IR, IS et titres privés sont séparées ; sans cotisations connues sur le court terme, le total reste provisoire. Les moins-values reportables et la compensation de plusieurs actifs ne sont pas automatisées.</p>
    <p>Location meublée : seuils micro 2026, statut LMP distinct des cotisations sociales, amortissements plafonnés et réintégration à la revente selon le CGI 150 VB. Les cotisations requises sont saisies d’après l’Urssaf. Les reports de déficit et amortissements doivent correspondre à la comptabilité réelle.</p>
    <p>Revenus fonciers : intérêts imputés en priorité, plafond énergétique conditionnel, reports par millésime et dépenses identiques entre régimes. Assurance-vie : solde social réel fourni par l’assureur et assiettes successorales renseignées ; les cas historiques particuliers demandent un calcul adapté.</p>
    <p>Prêt : échéancier arrondi au centime, assurance sur capital initial ou restant dû, taux nul et frais. Le taux effectif est une estimation conditionnée à la saisie de tous les frais obligatoires ; le respect du taux d’usure n’est pas validé automatiquement. Investissement locatif : éligibilité, dates, plafonds et impôt disponible doivent être confirmés ; les nouveaux dispositifs non proposés ne sont pas implicitement couverts.</p>
    <Link href="/" className="inline-block underline">Retour aux simulateurs</Link>
  </article></MainLayout>;
}
