export interface Guide {
 slug:string; title:string; description:string; audience:'particulier'|'professionnel'; intro:string;
 sections:{title:string; paragraphs:string[]}[];
 example:{title:string; context:string; rows:[string,string][]; conclusion:string};
 documents:string[]; limits:string; tools:[string,string][]; sources:[string,string][];
}
const dg='https://www.impots.gouv.fr/particulier/';
export const guides:Guide[]=[
{
 slug:'frais-notaire-2026',title:'Frais de notaire 2026 : comprendre le montant à payer',
 description:'Décomposez les frais d’un achat immobilier : droits de mutation, émoluments, TVA et débours. Exemple de vente et pièces pour préparer votre calcul.',audience:'particulier',
 intro:'Le montant demandé à la signature ne correspond pas seulement à la rémunération de l’office. Une estimation utile sépare les taxes de mutation, les émoluments de l’acte, la publicité foncière et les frais du dossier. Cette décomposition permet aussi de comprendre pourquoi deux acquisitions de même prix peuvent produire des frais différents.',
 sections:[{title:'Commencer par la bonne opération',paragraphs:['Identifiez le département, la date de l’acte, la nature du bien et le régime fiscal de la vente. « Neuf » au sens commercial ne suffit pas à déterminer le régime de droits applicable. Dans le neuf relevant du taux réduit, l’assiette utilisée par le calculateur doit être celle hors TVA immobilière.','La hausse départementale temporaire ne s’applique pas de la même façon au primo-accédant éligible. Le taux doit être rapproché du tableau départemental et du dossier. Les frais de financement, de garantie ou de courtage sont à budgéter séparément.']},{title:'Lire la provision puis le décompte',paragraphs:['La provision prépare les dépenses attendues. Le décompte définitif reprend les taxes et frais effectivement liquidés. Comparez chaque ligne à sa base de calcul, plutôt que de chercher à retrouver un pourcentage global. Une remise éventuelle sur émoluments ne réduit pas les impôts reversés.','Dans le prétaxateur, choisissez l’acte de vente, renseignez le prix et le département, puis adaptez les formalités aux pièces réellement nécessaires. Conservez une copie de la simulation avec sa date : elle aide à expliquer un écart, mais ne remplace pas la taxe de l’acte.']}],
 example:{title:'Achat ancien de 250 000 €',context:'Métropole, acquisition ordinaire, taux départemental de 5 %, sans remise, mobilier ni exonération. Frais d’assiette arrondis à l’euro.',rows:[['Droits départementaux','12 500 €'],['Taxe communale','3 000 €'],['Frais d’assiette : 2,37 % de 12 500 €','296 €'],['Contribution de sécurité immobilière','250 €'],['Émolument de vente HT','2 394,75 €'],['TVA sur cet émolument','478,95 €'],['Sous-total des lignes calculées','18 919,70 €']],conclusion:'Il faut ajouter les formalités, débours et autres actes nécessaires. Ce sous-total n’est donc pas une proposition de provision définitive.'},
 documents:['Projet ou compromis de vente et ventilation du prix','Département et date prévue de signature','Justificatifs d’éligibilité à une exonération ou au régime primo-accédant','Offre de prêt, garanties et estimation des formalités'],
 limits:'Ventes complexes, Alsace-Moselle, territoires particuliers, mutations démembrées et réductions locales peuvent demander une taxation adaptée.',tools:[['/pretaxe','Calculer une prétaxe'],['/capacite-emprunt','Construire le budget d’acquisition']],sources:[[dg+'questions/jachete-un-bien-immobilier-quaurai-je-payer-comme-frais-au-notaire','DGFiP — composantes des frais'],['https://www.impots.gouv.fr/droits-denregistrement','DGFiP — tableaux départementaux'],['https://www.legifrance.gouv.fr/codes/id/LEGISCTA000032132058','Code de commerce — tarifs notariaux']]},
{
 slug:'droits-succession',title:'Droits de succession : calcul par héritier, étape par étape',description:'Passez de la part nette de chaque héritier aux droits de succession. Exemples chiffrés, abattements et distinction avec les frais des actes notariés.',audience:'particulier',
 intro:'Le calcul fiscal vient après la détermination de ce qui revient à chaque héritier. Saisir la valeur totale du patrimoine dans le champ d’un seul enfant peut donc produire un résultat sans rapport avec le dossier. Préparez d’abord l’actif, le passif et les parts civiles, puis calculez les droits individuellement.',
 sections:[{title:'Séparer trois montants',paragraphs:['L’actif net successoral, la part de l’héritier et les droits dus à l’État sont différents. Le régime matrimonial, la propriété des biens, les dispositions testamentaires et les droits du conjoint interviennent avant la liquidation fiscale.','Les abattements dépendent du lien de parenté et de leur disponibilité. Une donation antérieure peut avoir consommé une partie de l’abattement et des premières tranches. Les frais de déclaration, de notoriété ou d’attestation immobilière ne sont pas ces droits fiscaux.']},{title:'Utiliser le calculateur sans mélanger les parts',paragraphs:['Pour chaque héritier, saisissez sa part nette déjà déterminée. Renseignez séparément l’abattement consommé et la base taxable antérieure lorsque le dossier comporte un rappel. Le mode représentation demande également le nombre de représentants : il ne reconstitue pas l’arbre familial.','Imprimez un résultat par héritier et rapprochez leur total du dossier. Une différence de droits entre enfants peut avoir une explication dans les donations antérieures ; elle ne signifie pas nécessairement que leurs parts civiles sont différentes.']}],
 example:{title:'Trois situations fiscales simples',context:'Parts civiles déjà établies, pleine propriété, aucun handicap, rappel de donation ni exonération particulière. Droits arrondis à l’euro.',rows:[['Conjoint recevant une part nette de 200 000 €','0 € de droits'],['Enfant recevant une part nette de 200 000 €','18 194 € de droits'],['Deux enfants recevant chacun 100 000 €','0 € chacun si leurs abattements sont intacts']],conclusion:'Le dernier cas suppose des parts de 100 000 € réellement attribuées à chacun. Il ne suffit pas de diviser arbitrairement une succession pour choisir le calcul le moins taxé.'},
 documents:['Inventaire des biens et dettes du défunt','Situation matrimoniale, testament et actes de donation','Parts nettes civiles calculées pour chaque héritier','Historique fiscal des donations et justificatifs des exonérations'],limits:'Le module ne tranche pas les questions de réserve héréditaire, d’option du conjoint, de rapport civil ou de liquidation matrimoniale.',tools:[['/succession','Calculer les droits par héritier'],['/pretaxe','Estimer les frais des actes']],sources:[[dg+'questions/comment-dois-je-calculer-les-droits-de-succession','DGFiP — droits de succession'],[dg+'calcul-et-paiement-des-droits','DGFiP — barèmes et rappel fiscal']]},
{
 slug:'donation-enfants',title:'Donation aux enfants : combien donner sans droits ?',description:'Comprenez les abattements des donations, les dons familiaux et le rappel de quinze ans. Cas chiffrés et conditions à vérifier avant de transmettre.',audience:'particulier',
 intro:'La bonne question est le montant encore disponible entre un donateur et un bénéficiaire précis. L’abattement ne se mesure ni par compte bancaire ni par acte. Avant de comparer argent, bien immobilier et nue-propriété, rassemblez les donations déjà effectuées et définissez ce que vous souhaitez conserver.',
 sections:[{title:'Ne pas additionner des plafonds sans leurs conditions',paragraphs:['L’abattement parent-enfant ordinaire est de 100 000 € par couple donateur-bénéficiaire, renouvelable après quinze ans. Le don familial de somme d’argent de 31 865 € suit ses propres conditions, notamment d’âge, de lien de parenté et de déclaration.','Deux parents peuvent intervenir, mais chacun dispose de son propre historique et doit transmettre un bien ou des fonds qu’il peut effectivement donner. Les exonérations spéciales ne doivent pas être présumées intactes lorsque d’autres dons ont déjà été réalisés.']},{title:'L’encadré logement à vérifier en 2026',paragraphs:['Un dispositif temporaire concerne certains dons d’argent affectés à un logement neuf ou à des travaux énergétiques : période du 15 février 2025 au 31 décembre 2026, plafonds et conditions d’affectation spécifiques. Le montant maximal ne suffit pas : délai d’emploi, usage du logement et durée de conservation doivent être examinés.','Préparez une fiche par donateur et par enfant. Dans le calculateur, sélectionnez le bénéficiaire avant de lire le résultat ; puis saisissez la donation antérieure et sa date si le cas simple de rappel correspond au dossier. Les antécédents complexes demandent une reconstitution détaillée.']}],
 example:{title:'Don de 200 000 € à un enfant',context:'Un parent, abattement intact, pleine propriété, sans don d’argent spécialement exonéré ni Dutreil.',rows:[['Valeur donnée','200 000 €'],['Abattement disponible','100 000 €'],['Base soumise au barème','100 000 €'],['Droits avant arrondi fiscal','18 194,35 €']],conclusion:'Avec un don antérieur, le calcul peut changer même si le nouveau montant est identique. Une économie fiscale ne répond pas à elle seule aux questions d’équité familiale ou de ressources futures du donateur.'},
 documents:['Identité, lien de parenté et âges des parties','Donations enregistrées et dates des précédents dons','Évaluation et titre de propriété du bien transmis','Projet d’utilisation des fonds pour une exonération conditionnelle'],limits:'Le calcul par couple donateur-bénéficiaire ne constitue pas un plan de transmission familial complet. Une donation immobilière nécessite un acte notarié.',tools:[['/donation','Simuler une donation'],['/succession','Comparer avec une succession']],sources:[[dg+'calcul-et-paiement-des-droits','DGFiP — droits de donation'],[dg+'questions/que-puis-je-donner-mes-enfants-petits-enfants-sans-avoir-payer-de-droits','DGFiP — dons familiaux et logement'],[dg+'dons-exoneres','DGFiP — conditions et déclaration']]},
{
 slug:'revente-lmnp-amortissements',title:'Revente LMNP : quel effet des amortissements sur l’impôt ?',description:'Comparez l’effet des amortissements déduits sur la plus-value LMNP. Exemple de revente, durée de détention et exceptions à vérifier avec la comptabilité.',audience:'particulier',
 intro:'Un amortissement peut réduire le bénéfice taxable pendant la location sans être une dépense de trésorerie. À la revente, son effet fiscal doit être examiné séparément. Une comparaison micro/réel limitée à la première année ne raconte donc pas tout le parcours de l’investissement.',
 sections:[{title:'Retrouver le bon montant en comptabilité',paragraphs:['Pour les cessions soumises aux règles nouvelles depuis février 2025, certains amortissements immobiliers effectivement déduits minorent le prix d’acquisition retenu pour la plus-value. Ne reprenez pas simplement la dotation théorique multipliée par le nombre d’années.','Distinguez amortissements comptabilisés, déduits et reportés. Le mobilier ne doit pas être réintégré comme s’il était l’immeuble vendu. Certaines résidences et certains amortissements de travaux relèvent d’exceptions précises : une appellation commerciale « senior » n’est pas une preuve suffisante.']},{title:'Comparer l’exploitation et la sortie',paragraphs:['Commencez par l’onglet annuel du module LMNP avec les charges et reports réels. Puis remplissez l’onglet de revente à partir du plan comptable. Le statut LMNP ou LMP se vérifie à la cession ; le régime professionnel relève d’un autre calculateur.','Pour décider entre deux options, conservez les mêmes hypothèses de prix, durée et frais. Un avantage annuel doit être rapproché du surcoût éventuel à la vente, mais aussi des frais comptables et de la trésorerie. Le calcul n’anticipe pas une évolution future de la loi.']}],
 example:{title:'Même vente, deux bases de comparaison',context:'Acquisition 2022, vente en 2026 avant cinq années révolues ; prix d’achat 200 000 €, frais retenus 15 000 €, vente 250 000 €, aucun autre frais ni exonération.',rows:[['Sans amortissement réintégrable : plus-value','35 000 €'],['IR 19 % + prélèvements 17,2 %','12 670 €'],['Avec 20 000 € d’amortissements réintégrables : plus-value','55 000 €'],['IR + prélèvements + surtaxe lissée de 850 €','20 760 €'],['Écart de fiscalité de cession','8 090 €']],conclusion:'L’exemple ne mesure pas l’économie obtenue pendant la location. Il montre pourquoi la sortie doit faire partie de la comparaison et pourquoi la surtaxe peut amplifier l’écart.'},
 documents:['Acte d’acquisition et projet de vente','Tableau des amortissements effectivement déduits','Ventilation terrain, immeuble, mobilier et travaux','Déclarations et statut fiscal de l’année de cession'],limits:'Module de revente dédié aux règles 2026 et à la pleine propriété ; situations démembrées, indivises ou professionnelles à traiter dans le parcours adapté.',tools:[['/lmnp','Calculer la fiscalité LMNP'],['/plusvalue-pro','Examiner une cession professionnelle']],sources:[[dg+'questions/je-vends-un-bien-immobilier-donne-en-location-meublee-comment-se-calcule-la','DGFiP — revente meublée'],[dg+'plus-values-imposees','DGFiP — calcul immobilier'],['https://bofip.impots.gouv.fr/bofip/8597-PGP.html/identifiant=BOI-RFPI-TPVIE-20-20230718','BOFiP — surtaxe immobilière']]},
{
 slug:'sci-ir-is-revente',title:'SCI à l’IR ou à l’IS : comparer jusqu’à la revente',description:'Comparez résultat fiscal, trésorerie, dividendes et revente d’une SCI. Exemple annuel et méthode pour distinguer argent en société et revenu personnel.',audience:'particulier',
 intro:'Le taux d’impôt le plus faible n’est pas nécessairement le meilleur résultat personnel. À l’IS, de l’argent peut rester dans la société et supporter une autre imposition lors de sa distribution. À l’IR, le bénéfice est imposé chez les associés même s’ils ne le retirent pas.',
 sections:[{title:'Suivre quatre colonnes différentes',paragraphs:['Séparez loyers encaissés, charges décaissées, résultat fiscal et argent disponible. L’amortissement réduit le résultat à l’IS sans sortir de trésorerie ; le capital remboursé à la banque réduit la trésorerie sans constituer une charge déductible.','Le taux réduit d’IS suppose des conditions propres à la société. Une comparaison ne doit pas le sélectionner automatiquement. Les dividendes et intérêts de compte courant ne suivent pas toujours la même base d’impôt.']},{title:'Ajouter la cession et le retour de l’argent',paragraphs:['À l’IR, le calcul de plus-value immobilière tient notamment compte de la durée. À l’IS, la valeur nette comptable intègre les amortissements. Après l’impôt de la société, distinguez remboursement d’une dette envers l’associé et distribution du bénéfice.','Utilisez le simulateur SCI pour examiner une année réelle. Le comparateur achat–location–revente suit un scénario de location nue, en direct et en SCI IS, sans distribution intermédiaire. Son résultat dépend du prix de vente saisi et n’est pas une recommandation automatique de constitution de société.']}],
 example:{title:'Une année, sans emprunt',context:'Loyers 15 000 €, charges communes 3 000 €, TMI 30 %. SCI IS : comptabilité supplémentaire 1 200 €, amortissement 5 000 €, IS de 25 %, aucune distribution.',rows:[['Direct : base avant forfait de 20 €','12 000 €'],['Direct : IR + PS sur cette base simplifiée','5 664 €'],['SCI IS : résultat comptable','5 800 €'],['IS à 25 %','1 450 €'],['Trésorerie gardée dans la SCI','9 350 €']],conclusion:'Les 9 350 € ne sont pas un revenu net immédiatement reçu par l’associé. La distribution et la revente doivent encore être étudiées. Le module direct ajoute le forfait de 20 € par local dans son calcul détaillé.'},
 documents:['Comptes et bilan de la société','Échéancier du prêt et plan d’amortissement','Convention et solde du compte courant','Projet de distribution, prix et date de revente'],limits:'L’option IS peut engager durablement la stratégie. Transmission, IFI, frais de société et situations d’associés différents demandent un examen distinct.',tools:[['/sci','Comparer une année de SCI'],['/strategie-immobiliere','Comparer jusqu’à la revente']],sources:[[dg+'societe-civile-immobiliere','DGFiP — SCI'],['https://entreprendre.service-public.gouv.fr/vosdroits/F23575','Service Public — impôt sur les sociétés'],[dg+'les-revenus-mobiliers','DGFiP — distributions et revenus mobiliers']]},
{
 slug:'plus-value-immobiliere',title:'Plus-value immobilière : frais, travaux et exonérations',description:'Préparez un calcul de plus-value immobilière avec frais, travaux, durée de détention et quote-part. Exemple à 22 ans et justificatifs à rassembler.',audience:'particulier',
 intro:'Le prix de vente moins le prix d’achat donne un premier écart, pas directement l’impôt. Frais admissibles, travaux, durée et exonérations changent l’assiette. Un calcul documenté évite de confondre une dépense réellement supportée avec une majoration fiscalement admise.',
 sections:[{title:'Reconstituer acquisition et cession',paragraphs:['Utilisez les valeurs et dates des actes. Dans une indivision, prix et frais doivent suivre la même quote-part. Pour un droit démembré, la valeur fiscale à retenir ne se déduit pas automatiquement de la valeur actuelle de la pleine propriété.','Pour un achat à titre onéreux, examinez frais réels admissibles ou forfait d’acquisition. Pour les travaux, vérifiez les justificatifs, l’absence de double déduction et, lorsque les conditions sont réunies, le forfait après plus de cinq ans.']},{title:'Lire les deux abattements séparément',paragraphs:['L’impôt sur la plus-value et les prélèvements sociaux n’ont pas le même calendrier d’abattement. L’absence d’IR ne signifie donc pas que la cession est totalement exonérée. Une surtaxe peut également s’ajouter aux plus-values imposables élevées.','Dans le calculateur, commencez sans exonération puis activez uniquement celles dont les conditions sont établies. Le net fiscal ne retranche pas automatiquement le prêt encore dû : utilisez le comparateur de sortie pour reconstituer les fonds réellement disponibles.']}],
 example:{title:'100 000 € de plus-value brute après 22 ans',context:'Cas ordinaire de résident, aucune exonération supplémentaire ; durée de 22 années entièrement révolues.',rows:[['Abattement IR','100 %'],['Impôt sur la plus-value','0 €'],['Abattement social','28 %'],['Assiette des prélèvements','72 000 €'],['Prélèvements à 17,2 %','12 384 €']],conclusion:'À 22 ans, ce cas reste soumis aux prélèvements sociaux. Le calcul exact utilise les dates de l’acte, pas une approximation en nombre de jours divisés par 365.'},
 documents:['Acte d’achat, de donation ou de succession à l’origine du bien','Factures de frais et travaux, avec traitement fiscal antérieur','Quote-part et actes relatifs au démembrement','Pièces justifiant une résidence principale ou autre exonération'],limits:'Résidence principale réelle, remploi, expropriation, non-résidence et opérations exceptionnelles obéissent à des conditions distinctes.',tools:[['/plusvalue','Calculer la plus-value'],['/strategie-immobiliere','Passer au net après remboursement du prêt']],sources:[[dg+'plus-values-imposees','DGFiP — plus-values imposées'],['https://bofip.impots.gouv.fr/bofip/8597-PGP.html/identifiant=BOI-RFPI-TPVIE-20-20230718','BOFiP — surtaxe et lissages']]},
{
 slug:'deficit-foncier-reports',title:'Déficit foncier : calcul, imputation et reports',description:'Distinguez intérêts, travaux et autres charges pour calculer le déficit foncier. Exemple chiffré, imputation globale et suivi des reports sur dix ans.',audience:'particulier',
 intro:'Un déficit comptable de trésorerie n’est pas nécessairement un déficit foncier. Le capital remboursé à la banque n’est pas déductible. Et la part du déficit provenant des intérêts ne s’impute pas sur le revenu global comme les autres dépenses.',
 sections:[{title:'Classer avant de totaliser',paragraphs:['Les loyers s’imputent d’abord sur les intérêts et frais assimilés admissibles. Les autres charges viennent ensuite. Le déficit hors intérêts peut s’imputer sur le revenu global dans la limite applicable ; le surplus et la fraction provenant des intérêts suivent les revenus fonciers futurs.','Les travaux doivent être qualifiés : réparation, entretien ou amélioration ne se confondent pas avec construction, reconstruction ou agrandissement. La majoration énergétique exige des conditions documentées ; la simple présence d’une facture de rénovation ne suffit pas.']},{title:'Conserver les millésimes',paragraphs:['Constituez une ligne par année d’origine du déficit. Un total sans date peut faire utiliser un report expiré ou consommer les déficits dans le mauvais ordre. Le module foncier suit les reports renseignés par ancienneté sur dix ans.','Comparez micro et réel avec les mêmes dépenses effectivement payées. Une déduction fiscale n’efface pas la sortie de trésorerie. Activez le mode foyer avant/après pour voir l’effet d’un changement de tranche, dans son périmètre ordinaire.']}],
 example:{title:'Les intérêts dépassent les loyers',context:'Loyers 15 000 €, intérêts 18 000 €, autres charges déductibles 20 000 €, plafond global ordinaire et revenu global suffisant.',rows:[['Déficit total','23 000 €'],['Fraction venant des intérêts','3 000 €'],['Imputation sur le revenu global','10 700 €'],['Report sur revenus fonciers','12 300 €'],['Économie IR indicative à TMI constante de 30 %','3 210 €']],conclusion:'Les 3 210 € ne sont pas une économie supplémentaire de prélèvements sociaux sur le revenu global. La location doit être maintenue dans les conditions légales pour préserver l’imputation.'},
 documents:['Déclaration 2044 et reports des années antérieures','Échéancier distinguant intérêts, assurance et principal','Factures de travaux et justificatifs de paiement','Baux, dates de location et diagnostics si dispositif énergétique'],limits:'Revenu global insuffisant, travaux non déductibles, démembrement et dispositifs spéciaux nécessitent un traitement adapté ; le report global non absorbé n’est pas reconstitué automatiquement.',tools:[['/revenus-fonciers','Calculer et suivre le déficit'],['/relance-logement','Examiner l’amortissement Relance logement']],sources:[['https://bofip.impots.gouv.fr/bofip/4142-PGP.html/identifiant=BOI-RFPI-BASE-30-20-20250916','BOFiP — déficits fonciers'],['https://www.economie.gouv.fr/particuliers/gerer-mon-argent/investir-dans-limmobilier/tout-savoir-sur-le-deficit-foncier','Ministère de l’Économie — déficit foncier']]},
{
 slug:'donation-nue-propriete',title:'Donation de nue-propriété : coût et conséquences',description:'Comprenez la valeur fiscale d’une donation de nue-propriété, les droits estimés et les conséquences de l’usufruit. Exemple à 65 ans et pièces utiles.',audience:'particulier',
 intro:'Donner la nue-propriété permet de transmettre un droit tout en conservant un usufruit. La réduction de la base taxable n’épuise pas le sujet : occupation, revenus, travaux, vente future et besoins du donateur doivent être organisés dans l’acte.',
 sections:[{title:'Valeur fiscale et valeur économique',paragraphs:['Le barème fiscal de l’usufruit viager dépend de l’âge de l’usufruitier. Il permet de déterminer la fraction taxable dans les opérations auxquelles il s’applique. Ce pourcentage n’est pas une table universelle de prix pour un viager ou une vente entre parties.','Le montant donné doit correspondre à une valeur vénale justifiable. Pour des parts sociales, on évalue d’abord les parts ; on ne remplace pas cette étape par le seul prix de l’immeuble détenu par la société.']},{title:'Préparer les conséquences concrètes',paragraphs:['Discutez la répartition des dépenses, les pouvoirs de gestion et le sort du prix en cas de vente. Le calculateur chiffre des droits fiscaux ; il ne rédige pas les clauses et ne détermine pas si la transmission protège suffisamment les revenus du donateur.','L’IFI suit ses propres règles : le démembrement ne produit pas automatiquement une économie pour l’usufruitier. Les exceptions doivent être rapprochées de l’origine des droits. Comparer donation et succession suppose aussi le même patrimoine, les mêmes bénéficiaires et les donations antérieures.']}],
 example:{title:'Bien de 300 000 €, usufruitier de 65 ans',context:'Donation de la nue-propriété entière à un enfant, abattement intact, sans autre réduction.',rows:[['Valeur fiscale de l’usufruit','40 %, soit 120 000 €'],['Valeur de la nue-propriété donnée','60 %, soit 180 000 €'],['Abattement parent-enfant','100 000 €'],['Base taxable','80 000 €'],['Droits avant arrondi fiscal','14 194,35 €']],conclusion:'Il faut ajouter les frais de l’acte. La fiscalité n’est qu’une partie du choix : le donateur doit pouvoir conserver les droits et ressources dont il a besoin.'},
 documents:['Titre de propriété et évaluation du bien ou des parts','Âge et identité de l’usufruitier','Historique des donations au même bénéficiaire','Projet de clauses sur revenus, charges et vente'],limits:'Usufruit temporaire, réversion, quasi-usufruit et situations internationales demandent une analyse spécifique.',tools:[['/donation','Calculer la donation démembrée'],['/ifi','Examiner le patrimoine taxable']],sources:[['https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006310173','CGI 669 — évaluation fiscale des droits'],[dg+'calcul-et-paiement-des-droits','DGFiP — liquidation des donations'],[dg+'calcul-de-lifi','DGFiP — IFI']]},
{
 slug:'assurance-vie-70-ans',title:'Assurance-vie avant et après 70 ans : deux fiscalités',description:'Distinguez les règles de transmission de l’assurance-vie avant et après 70 ans. Exemples avec plusieurs bénéficiaires, abattements et certificat fiscal.',audience:'particulier',
 intro:'L’âge à la date du décès ne suffit pas à déterminer les droits. Il faut connaître les dates des versements, la date du contrat et les capitaux relevant de chaque régime. Le certificat de l’assureur permet de partir d’assiettes fiscales documentées.',
 sections:[{title:'Ne pas mélanger les abattements',paragraphs:['Pour les capitaux relevant de l’article 990 I, l’abattement de 152 500 € se mesure par bénéficiaire, tous contrats concernés sur la tête du même assuré. Il ne se multiplie pas en ouvrant plusieurs contrats.','Pour l’article 757 B, le plafond de 30 500 € est global et concerne les primes taxables après 70 ans, à répartir entre les bénéficiaires non exonérés. Les droits de succession et leurs abattements interviennent ensuite, avec ce qui a déjà été consommé ailleurs.']},{title:'Distinguer transmission et retrait',paragraphs:['Un rachat du vivant du souscripteur relève d’autres règles : fraction de produits, ancienneté du contrat, date des primes et abattement annuel. Le solde social de l’assureur évite de prélever à nouveau des produits déjà taxés.','Une transformation admissible chez le même assureur et un rachat suivi d’un versement sur PER ne sont pas interchangeables. Préparez une comparaison de frais, de fiscalité et de disponibilité. La conservation d’un ancien contrat n’est pas automatiquement préférable.']}],
 example:{title:'Deux bénéficiaires, puis un cas après 70 ans',context:'Contrat courant dans le périmètre du module, sans capital antérieur reçu, bénéficiaires non exonérés.',rows:[['400 000 € relevant de 990 I, moitié pour chacun','200 000 € par bénéficiaire'],['Après abattement individuel de 152 500 €','47 500 € taxables chacun'],['Prélèvement de 20 %','9 500 € chacun'],['Autre cas : 100 000 € de primes relevant de 757 B','69 500 € après abattement global de 30 500 €']],conclusion:'Dans le dernier cas, il reste à appliquer les règles successorales de chaque bénéficiaire. Les gains ne se traitent pas comme les primes dans cette assiette.'},
 documents:['Certificat fiscal de l’assureur et date du contrat','Dates des primes et assiettes avant/après 70 ans','Capitaux et abattements déjà utilisés tous contrats','Clause bénéficiaire et bases successorales déjà liquidées'],limits:'Contrats anciens exonérés, clause démembrée, primes manifestement exagérées et situations internationales ne sont pas réglés par ce seul calcul.',tools:[['/assurance-vie','Simuler rachat et transmission'],['/succession','Calculer les droits successoraux']],sources:[[dg+'lassurance-vie-et-le-pea-0','DGFiP — rachats'],['https://www.impots.gouv.fr/je-suis-beneficiaire-dune-assurance-vie','DGFiP — bénéficiaire d’assurance-vie'],['https://www.service-public.gouv.fr/particuliers/vosdroits/F34982','Service Public — PER']]},
{
 slug:'credit-immobilier-cout',title:'Crédit immobilier : mensualité, assurance et coût total',description:'Lisez un échéancier et comparez mensualité, assurance, frais et taux effectif. Exemple de prêt à taux fixe et méthode pour construire le budget d’achat.',audience:'particulier',
 intro:'Deux prêts de même taux nominal peuvent coûter différemment si leur durée, assurance ou frais diffèrent. Commencez par un budget mensuel soutenable, puis vérifiez le capital financé et le coût total. Le taux affiché en publicité ne décrit pas à lui seul une offre.',
 sections:[{title:'Comparer des flux comparables',paragraphs:['Le prêt amortissable à échéances constantes répartit chaque mensualité entre intérêts et capital. Avec une assurance sur le capital initial, la prime reste constante dans ce modèle ; sur capital restant dû, elle décroît. Les quotités des emprunteurs doivent être comprises dans le taux saisi.','Le taux effectif rapproche les fonds reçus et les paiements obligatoires. Des frais de garantie, de courtage ou de dossier omis peuvent sous-estimer ce taux. Le simulateur mensuel ne contrôle pas le TAEG contractuel ni le taux d’usure.']},{title:'Passer du prêt au prix du bien',paragraphs:['Dans le calcul de capacité, renseignez les revenus stables retenus et les crédits existants, assurances comprises. Le taux d’effort de référence n’est pas une promesse de financement : la banque examine aussi les charges de vie, les revenus et les garanties.','L’apport ne doit pas être ajouté intégralement au prix du bien si une partie sert aux frais. Réservez les frais de financement et d’acquisition, puis établissez une prétaxe. Une provision de 8 % est seulement une hypothèse budgétaire, pas un tarif notarial.']}],
 example:{title:'200 000 € sur vingt ans',context:'240 mensualités, taux nominal fixe 3,5 %, assurance constante à 0,30 % sur capital initial, hors frais.',rows:[['Mensualité hors assurance','1 159,92 €'],['Assurance mensuelle','50 €'],['Première mensualité totale','1 209,92 €'],['Assurance sur 240 mois','12 000 €']],conclusion:'La dernière échéance est ajustée au centime pour solder le capital. Une durée différente modifie à la fois la mensualité et le coût, même sans changement de taux.'},
 documents:['Offre de prêt et tableau d’amortissement','Coût et quotités d’assurance','Frais de dossier, garantie et courtage','Revenus, crédits en cours et apport réellement mobilisable'],limits:'Taux variable, différé, paliers, prêts combinés, remboursement anticipé et évolution des primes nécessitent d’autres flux.',tools:[['/pret','Calculer l’échéancier'],['/capacite-emprunt','Estimer capacité et budget']],sources:[['https://www.economie.gouv.fr/hcsf/mesures/mesure-relative-loctroi-de-credits-immobiliers','HCSF — conditions d’octroi'],['https://www.banque-france.fr/fr/a-votre-service/particuliers/connaitre-pratiques-bancaires-assurance/credit/taux-usure','Banque de France — taux d’usure et TAEG']]},
{
 slug:'relance-logement-2026',title:'Relance logement 2026 : conditions et amortissement',description:'Comprenez l’amortissement Jeanbrun dans le neuf et l’ancien réhabilité : base, plafond du foyer, prorata et conséquences fiscales à la revente.',audience:'particulier',
 intro:'Relance logement, également appelé dispositif Jeanbrun, ouvre une déduction d’amortissement sous conditions. Pour examiner un projet, il faut d’abord valider le logement et la location, puis calculer la déduction et son effet sur les revenus du foyer.',
 sections:[{title:'Vérifier l’opération avant le taux',paragraphs:['Le cadre publié vise certaines acquisitions d’immeubles collectifs entre le 21 février 2026 et le 31 décembre 2028, destinées à une location nue principale sous engagement. L’ancien demande une qualification des travaux ; notre simulateur traite la réhabilitation lourde avec au moins 30 % du prix en travaux.','Les plafonds de loyer et de ressources ainsi que l’absence de lien familial interdit doivent être vérifiés. Un loyer modéré seul ne valide pas l’opération. Les projets de réforme ne sont pas appliqués comme s’ils étaient déjà en vigueur.']},{title:'Calculer la déduction, puis l’économie',paragraphs:['La base exclut forfaitairement 20 % au titre du foncier. Dans le neuf, les taux annuels sont de 3,5 %, 4,5 % ou 5,5 % selon le niveau de location ; dans l’ancien traité, 3 %, 3,5 % ou 4 %. Le premier exercice demande un prorata.','Le plafond se mesure au foyer et aux autres biens déjà amortis. Une majoration dépend de la proportion de revenus locatifs relevant de la catégorie requise, pas seulement du niveau sélectionné pour ce logement. À la revente, les amortissements déduits peuvent augmenter la plus-value imposable.']}],
 example:{title:'Neuf intermédiaire, année entière',context:'Prix hors frais 250 000 €, base éligible confirmée, aucun amortissement antérieur ni autre consommation du plafond. Revenu foncier positif suffisant.',rows:[['Base : 250 000 € × 80 %','200 000 €'],['Dotation : 200 000 € × 3,5 %','7 000 €'],['Plafond ordinaire disponible','8 000 €'],['Déduction retenue','7 000 €'],['Économie IR à TMI constante de 30 %','2 100 €']],conclusion:'L’effet social dépend aussi du revenu taxable restant. Une mise en service en cours d’année réduit la dotation ; l’économie réelle d’IR peut différer de la multiplication par la TMI.'},
 documents:['Acte d’acquisition et date d’achèvement','Qualification des travaux et diagnostics pour l’ancien','Bail, ressources du locataire et plafond de loyer','Option fiscale, engagement et suivi des plafonds du foyer'],limits:'Le simulateur chiffre une année et ne certifie pas l’éligibilité. Il exclut les autres voies d’assimilation au neuf, les reports antérieurs et une liquidation complète de la revente.',tools:[['/relance-logement','Calculer l’amortissement'],['/revenus-fonciers','Examiner le déficit foncier']],sources:[['https://www.service-public.gouv.fr/particuliers/vosdroits/F39735','Service Public — Relance logement'],['https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000053508409','Loi de finances 2026 — article 47'],['https://www.economie.gouv.fr/particuliers/impots-et-fiscalite/gerer-mon-impot-sur-le-revenu/loi-de-finances-2026-ce-qui-change-pour-les-particuliers','Ministère de l’Économie — loi de finances 2026']]},
{
 slug:'preparer-pretaxe',title:'Préparer une prétaxe : méthode et dossier pratique',description:'Construisez une prétaxe contrôlable : qualification de l’acte, assiettes, émoluments, taxes, formalités et pièces. Cas de vente et méthode de rapprochement.',audience:'professionnel',
 intro:'Une prétaxe utile laisse une piste de contrôle : qualification juridique, assiette, tarif et justificatif. Le total doit pouvoir être expliqué ligne par ligne. L’objectif est d’anticiper la provision puis de rapprocher le calcul des actes et diligences réellement accomplis.',
 sections:[{title:'Organiser le dossier de calcul',paragraphs:['Commencez par une fiche d’opération : acte principal, actes accessoires, territoire, date et parties. Un même prix ne constitue pas nécessairement la base de tous les émoluments, droits et contributions. Évitez de recopier l’assiette principale sur chaque ligne par défaut.','Pour chaque poste, conservez la règle choisie et la pièce qui justifie le montant. Distinguez taxe reversée, émolument taxable à la TVA, débours et formalité. Une saisie issue d’un document numérisé doit être rapprochée de l’original avant utilisation.']},{title:'Contrôler avant de transmettre la provision',paragraphs:['Vérifiez la nature de l’acte, les seuils du barème, les minima, la remise éventuelle et les majorations territoriales. Rapprochez les formalités des besoins du dossier : le fait qu’une case existe dans le logiciel ne signifie pas que la diligence est nécessaire.','Effectuez un contrôle indépendant sur une ou deux lignes significatives, puis vérifiez la somme, les arrondis et la TVA. Archivez les hypothèses avec la provision et expliquez les postes encore estimatifs. Au décompte définitif, recherchez les écarts de qualification ou d’assiette avant de conclure à une erreur de tarif.']}],
 example:{title:'Contrôle d’un émolument de vente de 300 000 €',context:'Barème ordinaire, hors remise et majoration territoriale ; calcul HT par tranches.',rows:[['6 500 € × 3,870 %','251,55 €'],['10 500 € × 1,596 %','167,58 €'],['43 000 € × 1,064 %','457,52 €'],['240 000 € × 0,799 %','1 917,60 €'],['Total HT','2 794,25 €']],conclusion:'Ce contrôle porte uniquement sur l’émolument de vente. Il ne liquide ni droits de mutation, ni formalités, ni débours, ni actes accessoires.'},
 documents:['Acte et pièces ayant servi à la qualification','Tableau des assiettes par poste','Référence tarifaire et date de vérification','Diligences prévues, justificatifs et contrôle des arrondis'],limits:'Les actes composites, exonérations particulières et tarifs territoriaux doivent être documentés. Une prétaxe n’est pas une certification de la rédaction juridique.',tools:[['/pretaxe','Ouvrir le prétaxateur'],['/cours-comptable-taxateur','Approfondir le cours comptable-taxateur']],sources:[['https://www.legifrance.gouv.fr/codes/id/LEGISCTA000032132058','Code de commerce — tarifs'],['https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000053593921','Arrêté tarifaire du 25 février 2026'],['https://www.impots.gouv.fr/droits-denregistrement','DGFiP — droits d’enregistrement']]}
];
export const guideBySlug=(slug:string)=>guides.find(g=>g.slug===slug);
