/** Compact data for calculator pages; article bodies stay in the server-rendered guides. */
export const toolResources:Record<string,{guides:[string,string][];pieces:string;limite:string}>={
 '/pretaxe':{guides:[['frais-notaire-2026','Frais d’acquisition expliqués'],['preparer-pretaxe','Méthode de prétaxe']],pieces:'Acte, prix ventilé, département, régime fiscal, pièces justifiant les formalités.',limite:'Les frais définitifs dépendent du dossier et des actes nécessaires.'},
 '/donation':{guides:[['donation-enfants','Donner à ses enfants'],['donation-nue-propriete','Transmettre la nue-propriété']],pieces:'Lien de parenté, valeur et propriété des biens, dates des donations et plafonds disponibles.',limite:'Un donateur et un bénéficiaire à la fois ; les rappels complexes nécessitent une reconstitution.'},
 '/succession':{guides:[['droits-succession','Calcul par héritier']],pieces:'Parts civiles nettes, passif admis et historique des donations.',limite:'La détermination des parts civiles précède le calcul fiscal.'},
 '/plusvalue':{guides:[['plus-value-immobiliere','Plus-value et justificatifs']],pieces:'Actes et dates, prix, frais admissibles, travaux et quote-part.',limite:'Vérifiez les conditions de chaque exonération ; le remboursement du prêt est distinct de l’impôt.'},
 '/lmnp':{guides:[['revente-lmnp-amortissements','LMNP : penser à la revente']],pieces:'Recettes du foyer, charges, amortissements déduits, reports et statut social.',limite:'Le statut LMP et l’affiliation sociale sont distincts. Cotisations et réintégration doivent correspondre au dossier.'},
 '/revenus-fonciers':{guides:[['deficit-foncier-reports','Déficit et reports'],['relance-logement-2026','Amortissement Relance logement']],pieces:'Loyers, factures, intérêts et assurance, déclarations et reports par année.',limite:'Une économie d’IR suppose un revenu global suffisant ; les travaux doivent être déductibles.'},
 '/sci':{guides:[['sci-ir-is-revente','SCI : comparer revenus et sortie']],pieces:'Comptes annuels, plan d’amortissement, échéancier, CCA et distribution.',limite:'La trésorerie de la société n’est pas intégralement un revenu disponible pour les associés.'},
 '/holding':{guides:[['sci-ir-is-revente','Trésorerie et retour aux associés']],pieces:'Structure du groupe, éligibilité mère-fille, comptes, frais et financement.',limite:'Fiscalité de sortie et frais d’entrée exclus du modèle holding ; pas d’intégration fiscale automatique.'},
 '/ifi':{guides:[],pieces:'Valeurs au 1er janvier, dettes admissibles, revenus et impôts de l’année précédente.',limite:'Prêts in fine, dettes familiales, participations et exonérations demandent une qualification spécifique.'},
 '/assurance-vie':{guides:[['assurance-vie-70-ans','Transmission avant et après 70 ans']],pieces:'Certificat fiscal de l’assureur, dates et montants des primes, capitaux déjà reçus et abattements consommés.',limite:'Les primes et gains relevant de chaque régime doivent venir du décompte de l’assureur.'},
 '/pret':{guides:[['credit-immobilier-cout','Comprendre le coût du crédit']],pieces:'Offre bancaire, assurance et quotités, frais et durée.',limite:'Prêt fixe à déblocage unique. L’estimation du taux effectif dépend des frais saisis.'},
 '/viager':{guides:[],pieces:'Valeur vénale, occupation, bouquet, horizon ou coefficient du professionnel.',limite:'Aucune table de mortalité intégrée ; le prix d’un viager ne se déduit pas du seul barème fiscal de l’usufruit.'},
 '/retraite':{guides:[],pieces:'Relevé de carrière, durées par régime, points et montants fournis par les caisses.',limite:'Pas de reconstitution intégrale des droits ni de tous les régimes particuliers.'},
 '/statut-juridique':{guides:[],pieces:'Activité, bénéfice, rémunération, capital et comptes courants.',limite:'Foyer et activité prédéfinis. Les modèles Urssaf ne remplacent pas le choix juridique lié au projet.'},
 '/plusvalue-pro':{guides:[],pieces:'Valeur d’origine, amortissements, cession, activité et cotisations estimées.',limite:'Compensations de plusieurs actifs et moins-values reportées non liquidées automatiquement.'},
 '/investissement-locatif':{guides:[['deficit-foncier-reports','Déficit et trésorerie'],['relance-logement-2026','Nouveau dispositif locatif']],pieces:'Prix, frais, loyers, vacance, charges, financement et conditions du dispositif.',limite:'Comparer aussi la fiscalité de sortie ; une réduction d’impôt n’est pas une garantie de rentabilité.'},
 '/capacite-emprunt':{guides:[['credit-immobilier-cout','Construire son financement'],['frais-notaire-2026','Prévoir les frais']],pieces:'Revenus retenus, crédits, apport, frais et assurance.',limite:'La banque conserve son appréciation du dossier et du reste à vivre.'},
 '/strategie-immobiliere':{guides:[['sci-ir-is-revente','Comprendre les deux scénarios']],pieces:'Budget d’achat, revenus et charges, crédit, valeur comptable et revente.',limite:'Location nue, scénario à paramètres 2026 constants et distribution seulement à la sortie.'},
 '/relance-logement':{guides:[['relance-logement-2026','Conditions de Relance logement']],pieces:'Dates, acte, travaux, bail, plafonds et amortissements du foyer.',limite:'Qualification du logement et des travaux à confirmer. Les reports antérieurs et la cession ne sont pas liquidés ici.'}
};
