/** Compact data for calculator pages; article bodies stay in the server-rendered guides. */
export const toolResources:Record<string,{guides:[string,string][];pieces:string;exemple:string;limite:string}>={
 '/pretaxe':{guides:[['frais-notaire-2026','Frais d’acquisition expliqués'],['preparer-pretaxe','Méthode de prétaxe']],pieces:'Acte, prix ventilé, département, régime fiscal, pièces justifiant les formalités.',exemple:'Vente de 300 000 € : émolument ordinaire HT de 2 794,25 €, hors remise et majoration ; ce montant ne comprend pas les droits et débours.',limite:'Les frais définitifs dépendent du dossier et des actes nécessaires.'},
 '/donation':{guides:[['donation-enfants','Donner à ses enfants'],['donation-nue-propriete','Transmettre la nue-propriété']],pieces:'Lien de parenté, valeur et propriété des biens, dates des donations et plafonds disponibles.',exemple:'Un parent donne 200 000 € à un enfant, abattement intact : 18 194,35 € de droits avant arrondi, hors autres exonérations et frais.',limite:'Un donateur et un bénéficiaire à la fois ; les rappels complexes nécessitent une reconstitution.'},
 '/succession':{guides:[['droits-succession','Calcul par héritier']],pieces:'Parts civiles nettes, passif admis et historique des donations.',exemple:'Part nette de 200 000 € pour un enfant sans rappel : droits arrondis de 18 194 €, hors frais des actes.',limite:'La détermination des parts civiles précède le calcul fiscal.'},
 '/plusvalue':{guides:[['plus-value-immobiliere','Plus-value et justificatifs']],pieces:'Actes et dates, prix, frais admissibles, travaux et quote-part.',exemple:'À 22 ans, une plus-value brute de 100 000 € supporte encore 12 384 € de prélèvements sociaux dans le cas ordinaire sans autre exonération.',limite:'Vérifiez les conditions de chaque exonération ; le remboursement du prêt est distinct de l’impôt.'},
 '/lmnp':{guides:[['revente-lmnp-amortissements','LMNP : penser à la revente']],pieces:'Recettes du foyer, charges, amortissements déduits, reports et statut social.',exemple:'12 000 € de recettes − 2 000 € de charges − 600 € de comptabilité − 5 000 € d’amortissement admissible = 4 400 € de base réelle, sans report.',limite:'Le statut LMP et l’affiliation sociale sont distincts. Cotisations et réintégration doivent correspondre au dossier.'},
 '/revenus-fonciers':{guides:[['deficit-foncier-reports','Déficit et reports'],['relance-logement-2026','Amortissement Relance logement']],pieces:'Loyers, factures, intérêts et assurance, déclarations et reports par année.',exemple:'15 000 € de loyers, 18 000 € d’intérêts et 20 000 € d’autres charges, forfait de 20 € compris : 10 700 € d’imputation globale et 12 300 € de report dans le cas ordinaire.',limite:'Une économie d’IR suppose un revenu global suffisant ; les travaux doivent être déductibles.'},
 '/sci':{guides:[['sci-ir-is-revente','SCI : comparer revenus et sortie']],pieces:'Comptes annuels, plan d’amortissement, échéancier, CCA et distribution.',exemple:'Avec 12 000 € de résultat avant amortissement et une dotation de 5 000 €, la base IS est de 7 000 € sans autre correction ; la dotation ne consomme pas de trésorerie.',limite:'La trésorerie de la société n’est pas intégralement un revenu disponible pour les associés.'},
 '/holding':{guides:[['sci-ir-is-revente','Trésorerie et retour aux associés'],['donation-nue-propriete','Transmission de droits']],pieces:'Structure du groupe, éligibilité mère-fille, comptes, frais et financement.',exemple:'Une remontée de 10 000 € éligible au régime mère-fille ordinaire produit une quote-part de 500 €, avant frais et déficits de la holding.',limite:'Fiscalité de sortie et frais d’entrée exclus du modèle holding ; pas d’intégration fiscale automatique.'},
 '/ifi':{guides:[['donation-nue-propriete','Démembrement et patrimoine']],pieces:'Valeurs au 1er janvier, dettes admissibles, revenus et impôts de l’année précédente.',exemple:'1 350 000 € nets taxables : 2 225 € après décote, avant autres réductions et plafonnement.',limite:'Prêts in fine, dettes familiales, participations et exonérations demandent une qualification spécifique.'},
 '/assurance-vie':{guides:[['assurance-vie-70-ans','Rachat et transmission']],pieces:'Certificat fiscal de l’assureur, dates et montants des primes, capitaux déjà reçus et abattements consommés.',exemple:'10 000 € de produits éligibles à 7,5 %, contrat de huit ans et abattement intact de 4 600 € : 405 € d’IR, prélèvements sociaux séparés.',limite:'Les primes et gains relevant de chaque régime doivent venir du décompte de l’assureur.'},
 '/pret':{guides:[['credit-immobilier-cout','Comprendre le coût du crédit']],pieces:'Offre bancaire, assurance et quotités, frais et durée.',exemple:'200 000 € sur 240 mois à 3,5 % : 1 159,92 € par mois hors assurance ; dernière échéance ajustée.',limite:'Prêt fixe à déblocage unique. L’estimation du taux effectif dépend des frais saisis.'},
 '/viager':{guides:[['donation-nue-propriete','Valeur fiscale et droits démembrés']],pieces:'Valeur vénale, occupation, bouquet, horizon ou coefficient du professionnel.',exemple:'Capital de rente de 120 000 €, scénario linéaire de dix ans à taux nul : 1 000 € par mois. C’est un horizon choisi, pas une espérance de vie.',limite:'Aucune table de mortalité intégrée ; le prix d’un viager ne se déduit pas du seul barème fiscal de l’usufruit.'},
 '/retraite':{guides:[['assurance-vie-70-ans','Préparer l’épargne et la transmission']],pieces:'Relevé de carrière, durées par régime, points et montants fournis par les caisses.',exemple:'Génération avril 1965 : âge légal de 63 ans et durée requise de 171 trimestres pour les départs concernés par le calendrier de septembre 2026.',limite:'Pas de reconstitution intégrale des droits ni de tous les régimes particuliers.'},
 '/statut-juridique':{guides:[['sci-ir-is-revente','Fiscalité et revenu disponible']],pieces:'Activité, bénéfice, rémunération, capital et comptes courants.',exemple:'Comparer un bénéfice de 60 000 € avec une même enveloppe totale permet de distinguer coût de rémunération, IS et dividendes ; le net dépend du scénario social.',limite:'Foyer et activité prédéfinis. Les modèles Urssaf ne remplacent pas le choix juridique lié au projet.'},
 '/plusvalue-pro':{guides:[['revente-lmnp-amortissements','Distinguer cession privée et professionnelle']],pieces:'Valeur d’origine, amortissements, cession, activité et cotisations estimées.',exemple:'Actif acquis 100 000 €, amortissements de 40 000 €, vendu 80 000 € : gain de 20 000 € avant frais et exonérations.',limite:'Compensations de plusieurs actifs et moins-values reportées non liquidées automatiquement.'},
 '/investissement-locatif':{guides:[['deficit-foncier-reports','Déficit et trésorerie'],['relance-logement-2026','Nouveau dispositif locatif']],pieces:'Prix, frais, loyers, vacance, charges, financement et conditions du dispositif.',exemple:'Plafond national B1, 50 m² utiles sans annexe : 11,80 × 50 × 1,08 = 637,20 €/mois en 2026, hors éventuelle modulation locale.',limite:'Comparer aussi la fiscalité de sortie ; une réduction d’impôt n’est pas une garantie de rentabilité.'},
 '/capacite-emprunt':{guides:[['credit-immobilier-cout','Construire son financement'],['frais-notaire-2026','Prévoir les frais']],pieces:'Revenus retenus, crédits, apport, frais et assurance.',exemple:'4 000 € de revenus, 35 % d’effort et 200 € de crédits existants : 1 200 € de mensualité disponible, assurance comprise.',limite:'La banque conserve son appréciation du dossier et du reste à vivre.'},
 '/strategie-immobiliere':{guides:[['sci-ir-is-revente','Comprendre les deux scénarios']],pieces:'Budget d’achat, revenus et charges, crédit, valeur comptable et revente.',exemple:'Un remboursement de capital de 10 000 € réduit la trésorerie de 10 000 € ; il n’efface pas 10 000 € de résultat fiscal.',limite:'Location nue, scénario à paramètres 2026 constants et distribution seulement à la sortie.'},
 '/relance-logement':{guides:[['relance-logement-2026','Conditions de Relance logement']],pieces:'Dates, acte, travaux, bail, plafonds et amortissements du foyer.',exemple:'Neuf intermédiaire de 250 000 €, année entière : base 200 000 €, dotation théorique 7 000 €, sous réserve du plafond disponible.',limite:'Qualification du logement et des travaux à confirmer. Les reports antérieurs et la cession ne sont pas liquidés ici.'}
};
