"use client";
import type { FoyerFiscal } from '@/lib/foyer';

export interface ChoixFoyer { actif: boolean; revenu: string; adultes: 1 | 2; enfants: string; confirme: boolean }
export const foyerInitial: ChoixFoyer = { actif:false, revenu:'', adultes:1, enfants:'0', confirme:false };
export function lireFoyer(f: ChoixFoyer): FoyerFiscal | undefined {
  if (!f.actif) return undefined;
  if (!f.confirme || !f.revenu.trim() || !f.enfants.trim()) throw Error('Renseignez les revenus et enfants du foyer et confirmez le périmètre du calcul avant/après.');
  const p = { revenu:Number(f.revenu), adultes:f.adultes, enfants:Number(f.enfants) };
  if (!Number.isFinite(p.revenu) || p.revenu < 0 || !Number.isInteger(p.enfants) || p.enfants < 0 || p.enfants > 10) throw Error('Paramètres du foyer invalides.');
  return p;
}
export default function FoyerFields({value,onChange}:{value:ChoixFoyer;onChange:(v:ChoixFoyer)=>void}) {
  return <fieldset className="col-span-full my-5 rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm text-slate-800 print:break-inside-avoid"><legend className="px-2 font-semibold">Affiner l’impôt sur le revenu</legend><label className="flex gap-3"><input type="checkbox" checked={value.actif} onChange={e=>onChange({...value,actif:e.target.checked})}/> Calculer l’impôt du foyer avant et après ce revenu, au lieu d’une TMI constante</label>{value.actif&&<div className="mt-4 space-y-4"><div className="grid gap-4 sm:grid-cols-3"><label>Autres revenus nets imposables annuels (€)<input aria-label="Autres revenus nets imposables du foyer" type="number" min="0" step="1" value={value.revenu} onChange={e=>onChange({...value,revenu:e.target.value})} className="mt-1 block w-full rounded border p-3"/></label><label>Imposition<select aria-label="Imposition du foyer" value={value.adultes} onChange={e=>onChange({...value,adultes:Number(e.target.value) as 1|2})} className="mt-1 block w-full rounded border p-3"><option value="1">Une personne imposée seule</option><option value="2">Couple marié ou pacsé, imposition commune</option></select></label><label>Enfants à charge exclusive<input aria-label="Enfants à charge exclusive" type="number" min="0" max="10" step="1" value={value.enfants} onChange={e=>onChange({...value,enfants:e.target.value})} className="mt-1 block w-full rounded border p-3"/></label></div><p>Revenus après déductions catégorielles (notamment frais professionnels), hors revenu du bien simulé. Barème 2026 sur les revenus 2025, conservé pour la projection : quotient familial ordinaire plafonné et décote inclus. Hors réductions, crédits, CSG déductible, contributions sur hauts revenus et seuil de recouvrement. Le résultat est une variation d’IR estimée, pas votre avis d’impôt.</p><label className="flex gap-3"><input type="checkbox" checked={value.confirme} onChange={e=>onChange({...value,confirme:e.target.checked})}/> Foyer résident en métropole, sans garde alternée, parent isolé, demi-part spéciale, veuvage particulier, revenu exceptionnel ou étranger. Je confirme que ce cas ordinaire correspond à ma simulation.</label><a className="inline-block underline" href="https://simulateur-ir-ifi.impots.gouv.fr/calcul_impot/2026/">Comparer avec le simulateur complet de la DGFiP</a></div>}</fieldset>;
}
