"use client";
import { useState } from 'react';
import Link from 'next/link';
import { capaciteEmprunt, relanceLogement, strategieImmobiliere, type Capacite, type Relance, type Strategie } from '@/lib/projets';
import FoyerFields,{foyerInitial,lireFoyer} from './FoyerFields';

const euro=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
type Champ={key:string;label:string;initial:string;help?:string};
const configs:Record<string,Champ[]>={
 capacite:[
 {key:'revenus',label:'Revenus mensuels nets avant impôt retenus (€)',initial:'4000',help:'Revenus stables retenus par la banque, à justifier. Aucun loyer futur ajouté automatiquement.'},
 {key:'credits',label:'Mensualités de crédits déjà dues, assurances comprises (€)',initial:'200'},
 {key:'effort',label:'Taux d’effort retenu (%)',initial:'35'},
 {key:'mois',label:'Durée du nouveau prêt en mois',initial:'240'},
 {key:'taux',label:'Taux nominal annuel (%)',initial:'3.5'},
 {key:'assurance',label:'Assurance annuelle sur capital initial (%)',initial:'0.3',help:'Taux total correspondant aux quotités de tous les emprunteurs.'},
 {key:'apport',label:'Apport mobilisable (€)',initial:'40000'},
 {key:'fraisCredit',label:'Frais de financement initiaux (€)',initial:'3000'},
 {key:'fraisAchatPct',label:'Provision pour frais d’acquisition (% du prix)',initial:'8',help:'Hypothèse de budget à remplacer par une prétaxe ; ce n’est pas un taux légal.'}],
 strategie:[
 {key:'prix',label:'Prix d’achat (€)',initial:'250000'},
 {key:'fraisAchat',label:'Frais d’acquisition réels admissibles (€)',initial:'19000',help:'Supposés capitalisés à l’IS et admissibles pour la plus-value des particuliers.'},
 {key:'loyers',label:'Loyers annuels encaissés, après vacance (€)',initial:'15000'},
 {key:'charges',label:'Charges annuelles communes hors crédit (€)',initial:'3000',help:'Charges déductibles et payées, hors amortissement et dépenses immobilisables. Forfait foncier de 20 € ajouté au calcul IR.'},
 {key:'credit',label:'Capital du prêt (€)',initial:'200000'},
 {key:'mois',label:'Durée du prêt en mois',initial:'240'},
 {key:'taux',label:'Taux nominal annuel (%)',initial:'3.5'},
 {key:'assurance',label:'Assurance annuelle sur capital initial (%)',initial:'0.3'},
 {key:'horizon',label:'Durée de détention, années entières',initial:'15'},
 {key:'hausse',label:'Évolution annuelle des loyers et charges (%)',initial:'0',help:'Scénario, pas une prévision. La comptabilité reste constante.'},
 {key:'vente',label:'Prix de revente envisagé (€)',initial:'300000',help:'Saisi indépendamment de la hausse des loyers.'},
 {key:'fraisVente',label:'Frais de cession déductibles (€)',initial:'10000'},
 {key:'terrain',label:'Part du terrain dans la valeur immobilisée (%)',initial:'20'},
 {key:'amortAnnees',label:'Durée moyenne d’amortissement du bâti (années)',initial:'40'},
 {key:'comptabilite',label:'Coût annuel supplémentaire de la SCI IS (€)',initial:'1200'},
 {key:'tmi',label:'TMI constante (%)',initial:'30'}],
 relance:[
 {key:'prix',label:'Prix d’acquisition hors frais (€)',initial:'250000'},
 {key:'travaux',label:'Travaux de réhabilitation admissibles, ancien uniquement (€)',initial:'0',help:'En neuf, saisir zéro. En ancien, au moins 30 % du prix dans le cas traité.'},
 {key:'annee',label:'Année calculée',initial:'2026'},
 {key:'dejaAmorti',label:'Amortissements déjà déduits pour ce bien (€)',initial:'0'},
 {key:'autresAmortissements',label:'Plafond annuel consommé par les autres logements (€)',initial:'0'},
 {key:'loyers',label:'Loyers encaissés dans l’année (€)',initial:'12000'},
 {key:'charges',label:'Autres charges déductibles hors amortissement (€)',initial:'2000',help:'Ne pas déduire une seconde fois les travaux incorporés dans la base.'},
 {key:'interets',label:'Intérêts et assurance du prêt déductibles (€)',initial:'3000'},
 {key:'tmi',label:'TMI pour le mode simple (%)',initial:'30'}]
};
export default function ProjectCalculators({mode}:{mode:'capacite'|'strategie'|'relance'}) {
 const [f,setF]=useState<Record<string,string>>(()=>Object.fromEntries(configs[mode].map(c=>[c.key,c.initial])));
 const [foyer,setFoyer]=useState(foyerInitial),[confirme,setConfirme]=useState(false),[isReduit,setIsReduit]=useState(false);
 const [ancien,setAncien]=useState(false),[niveau,setNiveau]=useState<Relance['niveau']>('intermediaire'),[plafond,setPlafond]=useState(8000),[dateAcquisition,setAcquisition]=useState('2026-02-21'),[debut,setDebut]=useState('2026-03-01');
 const [resultat,setResultat]=useState<React.ReactNode>(null),[erreur,setErreur]=useState('');
 const clear=()=>{setResultat(null);setErreur('');};
 const calculer=()=>{clear();try{
  const n:Record<string,number>={};for(const c of configs[mode]){if(!f[c.key].trim())throw Error('Renseignez tous les champs, zéro est accepté lorsque pertinent.');n[c.key]=Number(f[c.key]);}
  if(mode==='capacite'){
   const r=capaciteEmprunt(n as unknown as Capacite);
   setResultat(<><h2 className="text-2xl font-bold">Votre enveloppe estimée</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[['Mensualité disponible avec assurance',r.disponible],['Capital empruntable',r.capital],['Prix d’achat maximal estimé',r.budget],['Provision pour frais d’acquisition',r.fraisAchat],['Assurance mensuelle',r.assuranceMensuelle],['Revenu restant avant dépenses courantes',r.resteAvantVieCourante]].map(([t,v])=><div className="rounded-xl bg-indigo-50 p-4" key={String(t)}><dt>{t}</dt><dd className="mt-1 text-xl font-semibold">{euro(Number(v))}</dd></div>)}</dl>{r.financementInsuffisant&&<p role="alert">Les fonds disponibles ne couvrent pas les frais de financement.</p>}<p className="mt-5">Budget = (crédit + apport − frais de financement) ÷ (1 + provision de frais d’acquisition). Assurance constante sur capital initial. Comparez avec une offre bancaire réelle ; le reste après dépenses de vie, la stabilité des revenus et les garanties ne sont pas évalués automatiquement.</p><Link className="mt-4 inline-block underline" href="/pretaxe">Établir une prétaxe détaillée</Link></>);
  }else if(mode==='relance'){
   if(!ancien&&n.travaux!==0)throw Error('Les travaux séparés concernent le scénario ancien : saisir zéro pour le neuf.');
   const r=relanceLogement({...n,ancien,niveau,plafondFoyer:plafond,dateAcquisition,debut,confirme,foyer:lireFoyer(foyer)} as unknown as Relance);
   setResultat(<><h2 className="text-2xl font-bold">Déduction et effet fiscal de l’année</h2><p className="mt-4">Base amortissable : <strong>{euro(r.base)}</strong>. Taux : {(r.taux*100).toLocaleString('fr-FR',{maximumFractionDigits:1})} %. Prorata : {r.mois}/12.</p><p className="mt-3">Dotation théorique : {euro(r.theorique)} ; déduction après plafond et solde de base : <strong>{euro(r.deduction)}</strong>. Cumul déduit pour ce bien : {euro(r.cumul)}.</p><p className="mt-4 text-xs text-slate-600 sm:hidden print:hidden">Faites défiler le tableau horizontalement pour lire la comparaison.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[480px] text-left [&_th]:p-3 [&_td]:p-3"><thead><tr><th className="p-3">Fiscalité</th><th>Sans amortissement</th><th>Avec amortissement</th></tr></thead><tbody>{[['Revenu foncier imposable',r.sans.imposable,r.avec.imposable],['Déficit imputable au revenu global',r.sans.global,r.avec.global],['Déficit reportable sur le foncier',r.sans.report,r.avec.report],['Variation IR estimée',r.sans.ir,r.avec.ir],['Prélèvements sociaux',r.sans.ps,r.avec.ps]].map(([t,a,b])=><tr key={String(t)} className="border-t"><th className="p-3 font-normal">{t}</th><td>{euro(Number(a))}</td><td>{euro(Number(b))}</td></tr>)}</tbody></table></div><p className="mt-4 font-semibold">Écart d’IR : {euro(r.gainIR)} ; écart de prélèvements sociaux : {euro(r.gainPS)}.</p><p className="mt-3">Une déduction de {euro(r.deduction)} n’est pas un remboursement de ce montant. L’économie globale suppose des revenus suffisants ; les reports antérieurs et le report global non absorbé ne sont pas liquidés. La revente peut augmenter la plus-value du montant des amortissements déduits.</p></>);
  }else{
   if(!confirme)throw Error('Confirmez les hypothèses de la comparaison.');
   const r=strategieImmobiliere({...n,isReduit} as unknown as Strategie);
   setResultat(<><h2 className="text-2xl font-bold">Du financement à la sortie</h2><p className="mt-4">Apport initial : {euro(r.apport)} dans les deux scénarios. À l’IS, il est entièrement avancé en compte courant non rémunéré. Les besoins ultérieurs sont également financés par l’associé.</p><p className="mt-4 text-xs text-slate-600 sm:hidden print:hidden">Faites défiler le tableau horizontalement pour lire la comparaison.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[480px] text-left [&_th]:p-3 [&_td]:p-3"><thead><tr><th className="p-3">Résultat personnel</th><th>Détention directe</th><th>SCI IS</th></tr></thead><tbody><tr className="border-t"><th className="p-3 font-normal">Net personnel reçu lors de la vente</th><td>{euro(r.sortieIR)}</td><td>{euro(r.sortieIS)}</td></tr><tr className="border-t"><th className="p-3 font-semibold">Solde de tous les flux, apports inclus</th><td>{euro(r.netDirect)}</td><td>{euro(r.netPersonnelIS)}</td></tr></tbody></table></div><p className="mt-4">Direct : impôt sur la plus-value {euro(r.taxeVenteIR)}. SCI : amortissements cumulés {euro(r.amorti)} ; remboursement de CCA {euro(r.remboursementCCA)} ; dividende final {euro(r.dividende)} ; PFU sur ce dividende {euro(r.pfu)}.</p><p className="mt-3">L’IS de l’année de vente figure dans le tableau avec l’exploitation et la cession. Trésorerie restant en SCI après distribution : {euro(r.residuelSCI)} ; CCA non remboursé : {euro(r.ccaNonRembourse)}. Le solde est nominal, sans rendement alternatif ni actualisation ; il ne mesure pas une rentabilité garantie.</p><details className="mt-5" open><summary className="cursor-pointer py-3 font-semibold">Flux annuels et financement</summary><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-sm"><thead><tr>{['Année','Loyers','Intérêts + assurance','Capital remboursé','IR + PS nets','Cash direct','IS, vente incluse','Avance CCA','Cash en SCI'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{r.lignes.map(l=><tr className="border-t" key={l.annee}><td className="p-2">{l.annee}</td>{[l.loyers,l.interets,l.principal,l.ir,l.cashIR,l.is,l.avance,l.cashIS].map((v,i)=><td key={i} className="p-2">{euro(v)}</td>)}</tr>)}</tbody></table></div></details></>);
  }
 }catch(e){setErreur(e instanceof Error?e.message:'Calcul indisponible.');}};
 return <div className="mt-8 space-y-6"><div className="grid gap-5 rounded-2xl border bg-slate-50 p-5 md:grid-cols-2">{configs[mode].map(c=><label key={c.key} className="text-sm font-medium">{c.label}<input aria-label={c.label} type="number" min={c.key==='hausse'?'-99':0} step="any" value={f[c.key]} onChange={e=>{setF({...f,[c.key]:e.target.value});clear();}} className="mt-2 block w-full rounded-lg border bg-white p-3"/>{c.help&&<span className="mt-1 block text-xs font-normal text-slate-600">{c.help}</span>}</label>)}</div>
 {mode==='relance'&&<fieldset className="space-y-4 rounded-2xl border p-5"><legend className="px-2 font-semibold">Conditions du dispositif</legend><label className="flex gap-3"><input type="checkbox" checked={ancien} onChange={e=>{setAncien(e.target.checked);clear();}}/> Ancien avec réhabilitation lourde (sinon neuf ou VEFA)</label><label className="block">Niveau de location<select aria-label="Niveau de location" value={niveau} onChange={e=>{setNiveau(e.target.value as Relance['niveau']);clear();}} className="mt-2 block w-full max-w-full rounded border p-3 sm:mt-0 sm:ml-3 sm:inline-block sm:w-auto"><option value="intermediaire">Intermédiaire</option><option value="social">Social</option><option value="tres-social">Très social</option></select></label><label className="block">Plafond annuel applicable au foyer<select aria-label="Plafond annuel applicable au foyer" value={plafond} onChange={e=>{setPlafond(Number(e.target.value));clear();}} className="mt-2 block w-full max-w-full rounded border p-3 sm:mt-0 sm:ml-3 sm:inline-block sm:w-auto"><option value="8000">8 000 € — droit commun</option><option value="10000">10 000 € — proportion sociale éligible confirmée</option><option value="12000">12 000 € — proportion très sociale éligible confirmée</option></select></label><p className="text-sm">La majoration dépend de la proportion de revenus de tous les logements amortis du foyer (au moins 50 % dans la catégorie requise). Le niveau choisi pour ce seul bien ne suffit pas.</p><div className="grid gap-4 sm:grid-cols-2"><label>Date d’acquisition<input aria-label="Date d’acquisition Relance logement" type="date" min="2026-02-21" max="2028-12-31" value={dateAcquisition} onChange={e=>{setAcquisition(e.target.value);clear();}} className="mt-2 block rounded border p-3"/></label><label>Point de départ de l’amortissement<input aria-label="Début amortissement" type="date" value={debut} onChange={e=>{setDebut(e.target.value);clear();}} className="mt-2 block rounded border p-3"/></label></div><p className="text-sm">Premier jour du mois d’achèvement ou de l’acquisition si elle est postérieure. La proratisation retient ce mois. Le calendrier fourni doit correspondre aux pièces. Le modèle couvre la déduction annuelle sous plafond ordinaire de déficit global de 10 700 €, sans majoration énergétique.</p><label className="flex gap-3"><input type="checkbox" checked={confirme} onChange={e=>{setConfirme(e.target.checked);clear();}}/> Immeuble collectif éligible en pleine propriété, location nue principale pendant neuf ans, mise en location dans le délai légal, locataire hors foyer et sans lien de parenté ou d’alliance jusqu’au deuxième degré, plafonds de loyer et de ressources vérifiés, option régulière et absence de cumul interdit. Pour l’ancien : réhabilitation lourde éligible confirmée.</label><FoyerFields value={foyer} onChange={v=>{setFoyer(v);clear();}}/></fieldset>}
 {mode==='strategie'&&<fieldset className="space-y-4 rounded-2xl border p-5"><legend className="px-2 font-semibold">Hypothèses à confirmer</legend><label className="flex gap-3"><input type="checkbox" checked={isReduit} onChange={e=>{setIsReduit(e.target.checked);clear();}}/> Taux réduit IS applicable : exercice douze mois, CA ≤ 10 M€, capital libéré et détention éligible ≥ 75 %.</label><label className="flex gap-3"><input type="checkbox" checked={confirme} onChange={e=>{setConfirme(e.target.checked);clear();}}/> Cas de location nue, foyer résident, TMI constante et revenu global suffisant pour les déficits. Années complètes, cession après le nombre d’anniversaires indiqué. Aucune exonération personnelle ; charges courantes déductibles, aucun travaux immobilisé. Aucune distribution de SCI avant la vente.</label><p className="text-sm">Frais de crédit, constitution/liquidation de SCI, fiscalité internationale, donations et IFI exclus. Frais d’achat immobilisés à l’IS ; amortissement linéaire simplifié du bâti. Fiscalité 2026 constante. Déficits fonciers suivis dix ans ; pas de report global non absorbé. Le capital social et les réserves légales éventuelles ne sont pas simulés : le résultat porte sur la vente d’un immeuble suivie d’un remboursement de CCA et d’une distribution disponible, pas sur la liquidation de la société.</p></fieldset>}
 <div className="flex flex-wrap gap-3 print:hidden"><button onClick={calculer} className="rounded-lg bg-indigo-700 px-5 py-3 font-semibold text-white">Calculer</button>{resultat&&<button onClick={()=>window.print()} className="rounded-lg border px-5 py-3">Imprimer le résultat et les hypothèses</button>}</div>{erreur&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{erreur}</p>}{resultat&&<section aria-label="Résultats du projet" className="rounded-2xl border p-5 md:p-8">{resultat}</section>}</div>;
}
